#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

from vaultlib import TAG_REGISTRY, parse_frontmatter, render_frontmatter

TYPE_DIRECTORIES = {
    "summary": "summaries",
    "entity": "entities",
    "concept": "concepts",
    "comparison": "comparisons",
    "query": "queries",
}
TYPE_TITLES = {
    "summary": "Summaries",
    "entity": "Entities",
    "concept": "Concepts",
    "comparison": "Comparisons",
    "query": "Queries",
}
GENERATED_WARNING = (
    "<!-- Generated by scripts/rebuild_indexes.py; do not edit by hand. -->"
)


class IndexBuildError(RuntimeError):
    """Raised when source metadata is insufficient for a deterministic index."""


@dataclass(frozen=True)
class PageRecord:
    path: Path
    title: str
    page_type: str
    description: str


def page_sort_key(page: PageRecord) -> tuple[str, str]:
    return (page.title.casefold(), page.path.as_posix())


def _read_record(path: Path, expected_type: str) -> PageRecord:
    try:
        metadata = parse_frontmatter(
            path.read_text(encoding="utf-8"), source=path
        ).metadata
    except (OSError, ValueError) as error:
        raise IndexBuildError(f"{path}: {error}") from error
    values: dict[str, str] = {}
    for key in ("title", "type", "description"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value.strip():
            raise IndexBuildError(f"{path}: missing required {key}")
        values[key] = value.strip()
    if values["type"] != expected_type:
        raise IndexBuildError(
            f"{path}: type {values['type']!r} does not match {expected_type!r}"
        )
    return PageRecord(
        path=path,
        title=values["title"],
        page_type=values["type"],
        description=values["description"],
    )


def _typed_pages(vault_root: Path, page_type: str) -> tuple[PageRecord, ...]:
    directory = vault_root / "wiki" / TYPE_DIRECTORIES[page_type]
    records = [
        _read_record(path, page_type)
        for path in directory.glob("*.md")
        if path.name != "index.md"
    ]
    return tuple(sorted(records, key=page_sort_key))


def _project_pages(vault_root: Path) -> tuple[PageRecord, ...]:
    directory = vault_root / "projects"
    if not directory.exists():
        return ()
    records = [
        _read_record(path, "project")
        for path in directory.glob("*.md")
        if path.name != "index.md"
    ]
    return tuple(sorted(records, key=page_sort_key))


def _catalog_body(title: str, pages: tuple[PageRecord, ...]) -> str:
    lines = [GENERATED_WARNING, f"# {title}", ""]
    if pages:
        lines.extend(
            f"- [{page.title}]({page.path.name}) — {page.description}"
            for page in pages
        )
    else:
        lines.append("- No pages have been compiled in this section yet.")
    return "\n".join(lines) + "\n"


def _root_index() -> str:
    return f"""{GENERATED_WARNING}
# Nanochat LLM Wiki

This vault connects immutable research evidence and a pinned implementation
project to a compact, source-backed guide to building a small language model.

- [Read the vault guide](README.md)
- [Enter the compiled knowledge bundle](wiki/index.md)
- [Inspect pinned projects](projects/index.md)
- [Review the operations log](log.md)
"""


def _bundle_index() -> str:
    metadata = {
        "okf_version": "0.2",
        "title": "Nanochat LLM Wiki",
        "description": (
            "A source-backed guide to building a small language model end to end."
        ),
        "tag_registry": list(TAG_REGISTRY),
        "generated": {"by": "demo-vault/scripts/rebuild_indexes.py"},
    }
    body = f"""{GENERATED_WARNING}
# Nanochat LLM Wiki

The compiled layer turns the archived papers and pinned Nanochat project into
typed, interlinked knowledge.

- [Summaries](summaries/index.md)
- [Entities](entities/index.md)
- [Concepts](concepts/index.md)
- [Comparisons](comparisons/index.md)
- [Queries](queries/index.md)
- [Pinned projects](../projects/index.md)
- [Operations log](../log.md)
"""
    return render_frontmatter(metadata, body)


def build_indexes(vault_root: Path) -> dict[Path, str]:
    """Render every generated navigation file without touching the filesystem."""
    vault_root = vault_root.absolute()
    outputs: dict[Path, str] = {
        vault_root / "index.md": _root_index(),
        vault_root / "projects" / "index.md": _catalog_body(
            "Projects", _project_pages(vault_root)
        ),
        vault_root / "wiki" / "index.md": _bundle_index(),
    }
    for page_type, directory in TYPE_DIRECTORIES.items():
        outputs[vault_root / "wiki" / directory / "index.md"] = _catalog_body(
            TYPE_TITLES[page_type], _typed_pages(vault_root, page_type)
        )
    return outputs


def update_indexes(
    vault_root: Path, *, check: bool
) -> tuple[Path, ...]:
    """Check or write the complete deterministic index set."""
    outputs = build_indexes(vault_root)
    changed = tuple(
        path
        for path, expected in outputs.items()
        if not path.exists()
        or path.read_text(encoding="utf-8") != expected
    )
    if check:
        return changed
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild deterministic demo-vault navigation indexes."
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--vault",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    arguments = parser.parse_args(argv)
    try:
        changed = update_indexes(arguments.vault, check=arguments.check)
    except IndexBuildError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        if changed:
            for path in changed:
                print(f"stale {path.relative_to(arguments.vault.absolute())}")
            return 1
        print("indexes up to date")
        return 0
    if changed:
        for path in changed:
            print(f"updated {path.relative_to(arguments.vault.absolute())}")
    else:
        print("indexes already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
