#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from vaultlib import default_vault_root, parse_frontmatter, render_frontmatter

INDEX_FILE = "_index.md"
LEGACY_INDEX_FILE = "index.md"
LOG_FILE = "_log.md"
LEGACY_LOG_FILE = "log.md"
GENERATED_WARNING = "<!-- Generated by tools/llm-wiki/rebuild_indexes.py; do not edit by hand. -->"
DIRECTORY_DESCRIPTIONS = {
    "assets": "Flat binary evidence for the knowledge vault.",
    "raw": "Flat immutable source companions for the knowledge vault.",
    "inbox": "Unprocessed source candidates.",
    "output": "Polished reports and designs.",
    "playbooks": "Stable operational guidance.",
    "projects": "Portable repository cards; code knowledge stays with each repository.",
    "projects/code": "Ignored checkout-or-symlink bindings derived from project IDs.",
    "scratch": "Ephemeral working notes and hypotheses.",
    "wiki/summaries": "Narrative synthesis and entry points through the knowledge vault.",
    "tasks": "Current and historical work state.",
    "templates": "Opaque authoring templates for agents and humans.",
    "wiki": "Durable graph-ready knowledge and daily review notes.",
    "wiki/comparisons": "Decision-oriented comparisons of related approaches.",
    "wiki/concepts": "Reusable mechanisms, invariants, and ideas.",
    "wiki/daily": "Daily goals, active recall, and review plans.",
    "wiki/entities": "Durable named subjects with independent lookup value.",
    "wiki/queries": "Source-grounded durable answers.",
}


class IndexBuildError(RuntimeError):
    """Raised when metadata cannot support a deterministic OKF index."""


@dataclass(frozen=True)
class IndexRecord:
    section: str
    title: str
    link: str
    description: str


def _relative(vault_root: Path, path: Path) -> Path:
    return path.absolute().relative_to(vault_root.absolute())


def _is_hidden(path: Path) -> bool:
    return path.name.startswith(".") or path.name == "__pycache__"


def _is_opaque(vault_root: Path, path: Path) -> bool:
    parts = _relative(vault_root, path).parts
    return bool(parts) and (
        parts[0] in {"assets", "templates"}
        or parts[:2] == ("projects", "code")
        or parts[-1] == "assets"
    )


def owned_directories(vault_root: Path) -> tuple[Path, ...]:
    """Return every visible vault-owned directory, excluding opaque trees."""
    root = vault_root.absolute()
    if not root.is_dir():
        return ()
    directories: list[Path] = []
    pending = [root]
    while pending:
        directory = pending.pop()
        directories.append(directory)
        children = [
            child for child in directory.iterdir()
            if child.is_dir()
            and not child.is_symlink()
            and not _is_hidden(child)
            and not _is_opaque(root, child)
        ]
        pending.extend(sorted(children, reverse=True))
    return tuple(sorted(directories, key=lambda path: path.as_posix()))


def _page_record(path: Path) -> IndexRecord:
    try:
        metadata = parse_frontmatter(path.read_text(encoding="utf-8"), source=path).metadata
    except (OSError, ValueError) as error:
        raise IndexBuildError(f"{path}: {error}") from error
    values: dict[str, str] = {}
    for key in ("type", "title", "description"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value.strip():
            raise IndexBuildError(f"{path}: missing required {key}")
        values[key] = value.strip()
    return IndexRecord(values["type"], values["title"], path.name, values["description"])


def _directory_description(vault_root: Path, directory: Path) -> str:
    relative = _relative(vault_root, directory).as_posix()
    if relative in DIRECTORY_DESCRIPTIONS:
        return DIRECTORY_DESCRIPTIONS[relative]
    label = directory.name.replace("-", " ").replace("_", " ")
    return f"Browse the {label} collection."


def _directory_record(vault_root: Path, directory: Path) -> IndexRecord:
    return IndexRecord("Subdirectories", directory.name, f"{directory.name}/", _directory_description(vault_root, directory))


def _resource_record(path: Path) -> IndexRecord:
    suffix = path.suffix.lower().lstrip(".") or "file"
    return IndexRecord("Resources", path.name, path.name, f"Bundled {suffix} resource.")


def child_records(directory: Path, vault_root: Path) -> tuple[IndexRecord, ...]:
    records: list[IndexRecord] = []
    for child in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if _is_hidden(child) or child.name in {INDEX_FILE, LEGACY_INDEX_FILE, LEGACY_LOG_FILE}:
            continue
        if child.is_dir():
            records.append(_directory_record(vault_root, child))
        elif child.name == LOG_FILE:
            records.append(IndexRecord("Log", "Bundle history", LOG_FILE, "Oldest-first append-only record of material bundle changes."))
        elif child.suffix.lower() == ".md":
            records.append(_page_record(child))
        else:
            records.append(_resource_record(child))
    return tuple(records)


def _section_sort_key(section: str) -> tuple[int, str]:
    if section == "Subdirectories":
        return (0, section)
    if section in {"Resources", "Log"}:
        return (2, section)
    return (1, section.casefold())


def build_index(directory: Path, vault_root: Path, records: tuple[IndexRecord, ...]) -> str:
    grouped: dict[str, list[IndexRecord]] = defaultdict(list)
    for record in records:
        grouped[record.section].append(record)
    sections: list[str] = [GENERATED_WARNING]
    if not grouped:
        sections.extend(["# Contents", "", "* No entries yet."])
    else:
        for section in sorted(grouped, key=_section_sort_key):
            sections.extend([f"# {section}", ""])
            for record in sorted(grouped[section], key=lambda item: (item.title.casefold(), item.link)):
                sections.append(f"* [{record.title}]({record.link}) - {record.description}")
            sections.append("")
        while sections and not sections[-1]:
            sections.pop()
    body = "\n".join(sections) + "\n"
    return render_frontmatter({"okf_version": "0.2"}, body) if directory.absolute() == vault_root.absolute() else body


def build_indexes(vault_root: Path) -> dict[Path, str]:
    root = vault_root.absolute()
    return {
        directory / INDEX_FILE: build_index(directory, root, child_records(directory, root))
        for directory in owned_directories(root)
    }


def update_indexes(vault_root: Path, *, check: bool) -> tuple[Path, ...]:
    root = vault_root.absolute()
    outputs = build_indexes(root)
    changed = tuple(path for path, expected in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != expected)
    if not check:
        for path in changed:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[path], encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild hierarchical OKF indexes for an LLM Wiki vault.")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--vault", type=Path, default=default_vault_root())
    arguments = parser.parse_args(argv)
    try:
        changed = update_indexes(arguments.vault, check=arguments.check)
    except IndexBuildError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check and changed:
        for path in changed:
            print(f"stale {path.relative_to(arguments.vault.absolute())}")
        return 1
    if arguments.check:
        print("indexes up to date")
    elif changed:
        for path in changed:
            print(f"updated {path.relative_to(arguments.vault.absolute())}")
    else:
        print("indexes already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
