#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from vaultlib import default_vault_root, parse_frontmatter, render_frontmatter

INDEX_FILE = "_index.md"
LOG_FILE = "_log.md"
GENERATED_WARNING = "<!-- Generated by tools/llm-wiki/vault.py rebuild; do not edit by hand. -->"
OUTLINE_SPLIT_FACTOR = 20
OPAQUE_ROOT_FILES = {"package.json", "package-lock.json"}
DIRECTORY_DESCRIPTIONS = {
    "assets": "Flat binary evidence for the knowledge vault.",
    "raw": "Flat immutable source companions for the knowledge vault.",
    "inbox": "Unprocessed source candidates.",
    "output": "Polished reports and designs.",
    "playbooks": "Stable operational guidance.",
    "projects": "Portable repository cards; code knowledge stays with each repository.",
    "projects/code": "Ignored checkout-or-symlink bindings derived from project IDs.",
    "vaults": "Portable cards for federated knowledge vaults.",
    "vaults/bindings": "Ignored local bindings derived from knowledge-vault IDs.",
    "scratch": "Ephemeral working notes and hypotheses.",
    "wiki/summaries": "Narrative synthesis and entry points through the knowledge vault.",
    "tasks": "Current and historical work state.",
    "templates": "Opaque authoring templates for agents and humans.",
    "wiki": "Durable graph-ready knowledge and daily review notes.",
    "wiki/comparisons": "Decision-oriented comparisons of related approaches.",
    "wiki/concepts": "Reusable mechanisms, invariants, and ideas.",
    "wiki/daily": "Daily goals, active recall, and review plans.",
    "wiki/entities": "Durable named subjects with independent lookup value.",
    "wiki/queries": "Source-grounded durable answers.",
}


class IndexBuildError(RuntimeError):
    """Raised when metadata cannot support a deterministic OKF index."""


@dataclass(frozen=True)
class IndexRecord:
    section: str
    title: str
    link: str
    description: str
    topics: tuple[str, ...] = ()


@dataclass
class TopicNode:
    records: list[IndexRecord] = field(default_factory=list)
    children: dict[str, "TopicNode"] = field(default_factory=dict)


@dataclass(frozen=True)
class TopicSpec:
    title: str
    parent: str | None = None
    source_roots: tuple[tuple[str, tuple[str, ...]], ...] = ()


def _relative(vault_root: Path, path: Path) -> Path:
    return path.absolute().relative_to(vault_root.absolute())


def _is_hidden(path: Path) -> bool:
    return path.name.startswith(".") or path.name == "__pycache__"


def _is_opaque(vault_root: Path, path: Path) -> bool:
    parts = _relative(vault_root, path).parts
    return bool(parts) and (
        parts[0] in {"assets", "templates", "tools", "node_modules"}
        or parts[:2] in {("projects", "code"), ("vaults", "bindings")}
        or parts[-1] == "assets"
    )


def owned_directories(vault_root: Path) -> tuple[Path, ...]:
    """Return every visible vault-owned directory, excluding opaque trees."""
    root = vault_root.absolute()
    if not root.is_dir():
        return ()
    directories: list[Path] = []
    pending = [root]
    while pending:
        directory = pending.pop()
        directories.append(directory)
        children = [
            child for child in directory.iterdir()
            if child.is_dir()
            and not child.is_symlink()
            and not _is_hidden(child)
            and not _is_opaque(root, child)
        ]
        pending.extend(sorted(children, reverse=True))
    return tuple(sorted(directories, key=lambda path: path.as_posix()))


def _topic_label(value: str) -> str:
    normalized = value.strip().strip("/._").replace("_", "-")
    return " ".join(part.capitalize() for part in normalized.replace("-", " ").split())


def _load_topic_registry(vault_root: Path) -> dict[str, TopicSpec]:
    path = vault_root / "TAGS.md"
    try:
        metadata = parse_frontmatter(path.read_text(encoding="utf-8"), source=path).metadata
    except (OSError, ValueError):
        return {}
    raw = metadata.get("index_topics")
    if not isinstance(raw, dict):
        return {}
    registry: dict[str, TopicSpec] = {}
    for key, value in raw.items():
        if not isinstance(key, str) or not key.strip():
            continue
        if isinstance(value, str):
            registry[key] = TopicSpec(value.strip())
            continue
        if not isinstance(value, dict) or not isinstance(value.get("title"), str):
            continue
        roots: list[tuple[str, tuple[str, ...]]] = []
        source_roots = value.get("source_roots", [])
        if isinstance(source_roots, list):
            for root in source_roots:
                if not isinstance(root, dict) or not isinstance(root.get("prefix"), str):
                    continue
                topics = root.get("topics", [])
                if not isinstance(topics, list) or not all(isinstance(item, str) for item in topics):
                    continue
                roots.append((root["prefix"].strip("/"), tuple(item.strip() for item in topics if item.strip())))
        parent = value.get("parent")
        registry[key] = TopicSpec(
            value["title"].strip(),
            parent if isinstance(parent, str) and parent.strip() else None,
            tuple(roots),
        )
    return registry


def _topic_chain(key: str, registry: dict[str, TopicSpec]) -> tuple[str, ...]:
    keys: list[str] = []
    seen: set[str] = set()
    current: str | None = key
    while current and current in registry and current not in seen:
        seen.add(current)
        keys.append(current)
        current = registry[current].parent
    return tuple(registry[item].title for item in reversed(keys))


def _semantic_topics(
    metadata: dict[str, object],
    path: Path,
    registry: dict[str, TopicSpec],
) -> tuple[str, ...]:
    explicit = metadata.get("index_topics")
    if isinstance(explicit, list) and explicit and all(isinstance(item, str) and item.strip() for item in explicit):
        return tuple(str(item).strip() for item in explicit[:5])
    if isinstance(explicit, str) and explicit.strip():
        return (explicit.strip(),)

    tags = [str(tag) for tag in metadata.get("tags", []) if isinstance(tag, str)] \
        if isinstance(metadata.get("tags"), list) else []
    candidates = [tag for tag in tags if tag in registry]
    if not candidates:
        return ()
    selected = max(candidates, key=lambda tag: len(_topic_chain(tag, registry)))
    topics = list(_topic_chain(selected, registry))

    source_path = metadata.get("source_path")
    if isinstance(source_path, str) and source_path.strip():
        normalized_path = Path(source_path).as_posix().strip("/")
        roots = sorted(registry[selected].source_roots, key=lambda item: len(item[0]), reverse=True)
        matched = next((root for root in roots if normalized_path == root[0] or normalized_path.startswith(root[0] + "/")), None)
        derived: list[str] = []
        if matched:
            remainder = normalized_path[len(matched[0]):].strip("/")
            parts = [part for part in remainder.split("/") if part]
            directories = parts[:-1] if parts and "." in parts[-1] else parts
            derived = [*matched[1], *(_topic_label(part) for part in directories)]
        for part in derived:
            if part and part not in topics and len(topics) < 5:
                topics.append(part)
    return tuple(topics)


def _page_record(path: Path, registry: dict[str, TopicSpec]) -> IndexRecord:
    try:
        metadata = parse_frontmatter(path.read_text(encoding="utf-8"), source=path).metadata
    except (OSError, ValueError) as error:
        raise IndexBuildError(f"{path}: {error}") from error
    values: dict[str, str] = {}
    for key in ("type", "title", "description"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value.strip():
            raise IndexBuildError(f"{path}: missing required {key}")
        values[key] = " ".join(value.split())
    return IndexRecord(
        values["type"], values["title"], path.name, values["description"],
        _semantic_topics(metadata, path, registry),
    )


def _directory_description(vault_root: Path, directory: Path) -> str:
    relative = _relative(vault_root, directory).as_posix()
    if relative in DIRECTORY_DESCRIPTIONS:
        return DIRECTORY_DESCRIPTIONS[relative]
    label = directory.name.replace("-", " ").replace("_", " ")
    return f"Browse the {label} collection."


def _directory_record(vault_root: Path, directory: Path) -> IndexRecord:
    return IndexRecord("Subdirectories", directory.name, f"{directory.name}/", _directory_description(vault_root, directory))


def _resource_record(path: Path) -> IndexRecord:
    suffix = path.suffix.lower().lstrip(".") or "file"
    return IndexRecord("Resources", path.name, path.name, f"Bundled {suffix} resource.")


def child_records(
    directory: Path,
    vault_root: Path,
    registry: dict[str, TopicSpec],
) -> tuple[IndexRecord, ...]:
    records: list[IndexRecord] = []
    for child in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if _is_hidden(child) or _is_opaque(vault_root, child) or child.name in {INDEX_FILE, *OPAQUE_ROOT_FILES}:
            continue
        if child.is_dir():
            records.append(_directory_record(vault_root, child))
        elif child.name == LOG_FILE:
            records.append(IndexRecord("Log", "Bundle history", LOG_FILE, "Oldest-first append-only record of material bundle changes."))
        elif child.suffix.lower() == ".md":
            records.append(_page_record(child, registry))
        else:
            records.append(_resource_record(child))
    return tuple(records)


def _section_sort_key(section: str) -> tuple[int, str]:
    if section == "Subdirectories":
        return (0, section)
    if section in {"Resources", "Log"}:
        return (2, section)
    return (1, section.casefold())


def _topic_tree(records: list[IndexRecord]) -> TopicNode:
    root = TopicNode()
    for record in records:
        node = root
        for topic in record.topics:
            node = node.children.setdefault(topic, TopicNode())
        node.records.append(record)
    return root


def _index_title(directory: Path, vault_root: Path) -> str:
    relative = _relative(vault_root, directory)
    if not relative.parts:
        return "Vault Index"
    label = directory.name.replace("-", " ").replace("_", " ").strip()
    return f"{label.title()} Index"


def _render_topic_node(
    node: TopicNode,
    *,
    heading_level: int,
    context: str,
    lines: list[str],
) -> None:
    if heading_level > 6 and node.children:
        raise IndexBuildError(f"{context}: semantic topic hierarchy exceeds Markdown heading depth")
    for record in sorted(node.records, key=lambda item: (item.title.casefold(), item.link)):
        lines.append(f"- [{record.title}]({record.link}) - {record.description}")
    if node.records:
        lines.append("")
    for topic, child in sorted(node.children.items(), key=lambda item: item[0].casefold()):
        lines.extend([f"{'#' * heading_level} {topic}", ""])
        _render_topic_node(
            child,
            heading_level=heading_level + 1,
            context=f"{context} / {topic}",
            lines=lines,
        )


def build_index(directory: Path, vault_root: Path, records: tuple[IndexRecord, ...]) -> str:
    grouped: dict[str, list[IndexRecord]] = defaultdict(list)
    for record in records:
        if record.topics:
            grouped[record.topics[0]].append(IndexRecord(
                record.section,
                record.title,
                record.link,
                record.description,
                record.topics[1:],
            ))
        else:
            fallback = record.section if record.section in {"Subdirectories", "Resources", "Log"} else "Other"
            grouped[fallback].append(record)
    sections: list[str] = [GENERATED_WARNING, f"# {_index_title(directory, vault_root)}", ""]
    if not grouped:
        sections.append("No entries yet.")
    else:
        for section in sorted(grouped, key=_section_sort_key):
            sections.extend([f"## {section}", ""])
            _render_topic_node(
                _topic_tree(grouped[section]),
                heading_level=3,
                context=f"{directory.relative_to(vault_root) or Path('.')} / {section}",
                lines=sections,
            )
            sections.append("")
        while sections and not sections[-1]:
            sections.pop()
    normalized: list[str] = []
    for line in sections:
        if line or not normalized or normalized[-1]:
            normalized.append(line)
    body = "\n".join(normalized) + "\n"
    return render_frontmatter({"okf_version": "0.2"}, body) if directory.absolute() == vault_root.absolute() else body


def build_indexes(vault_root: Path) -> dict[Path, str]:
    root = vault_root.absolute()
    registry = _load_topic_registry(root)
    return {
        directory / INDEX_FILE: build_index(directory, root, child_records(directory, root, registry))
        for directory in owned_directories(root)
    }


def update_indexes(vault_root: Path, *, check: bool) -> tuple[Path, ...]:
    root = vault_root.absolute()
    outputs = build_indexes(root)
    changed = tuple(path for path, expected in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != expected)
    if not check:
        for path in changed:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[path], encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild hierarchical OKF indexes for an LLM Wiki vault.")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--vault", type=Path, default=default_vault_root())
    arguments = parser.parse_args(argv)
    try:
        changed = update_indexes(arguments.vault, check=arguments.check)
    except IndexBuildError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check and changed:
        for path in changed:
            print(f"stale {path.relative_to(arguments.vault.absolute())}")
        return 1
    if arguments.check:
        print("indexes up to date")
    elif changed:
        for path in changed:
            print(f"updated {path.relative_to(arguments.vault.absolute())}")
    else:
        print("indexes already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
