#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from vaultlib import (
    RepositoryRegistryError,
    default_vault_root,
    parse_frontmatter,
    parse_repository_registry,
    render_frontmatter,
)

INDEX_FILE = "_index.md"
LEGACY_INDEX_FILE = "index.md"
LOG_FILE = "_log.md"
LEGACY_LOG_FILE = "log.md"
GENERATED_WARNING = (
    "<!-- Generated by tools/llm-wiki/rebuild_indexes.py; "
    "do not edit by hand. -->"
)
DIRECTORY_DESCRIPTIONS = {
    "assets": "Flat binary evidence for the knowledge vault.",
    "raw": "Flat immutable source companions for the knowledge vault.",
    "examples": "Stable illustrative examples and viewer fixtures.",
    "projects": "Repository cards paired with self-contained code vaults.",
    "projects/code": "Ignored in-place VCS working copies registered by repository ID.",
    "summaries": "Narrative entry points through the knowledge bundle.",
    "entities": "Named datasets, model families, and other concrete subjects.",
    "concepts": "Focused explanations of language-model mechanisms.",
    "comparisons": "Decision-oriented comparisons of related approaches.",
    "queries": "Durable answers to recurring reader questions.",
}


class IndexBuildError(RuntimeError):
    """Raised when metadata cannot support a deterministic OKF index."""


@dataclass(frozen=True)
class IndexRecord:
    section: str
    title: str
    link: str
    description: str


def _relative(vault_root: Path, path: Path) -> Path:
    return path.absolute().relative_to(vault_root.absolute())


def _is_opaque(vault_root: Path, path: Path) -> bool:
    relative = _relative(vault_root, path)
    return (
        (len(relative.parts) == 1 and relative.parts[0] in {"assets", "code"})
        or (len(relative.parts) == 2 and relative.parts == ("projects", "code"))
        or (
            len(relative.parts) == 3
            and relative.parts[0] == "projects"
            and relative.parts[2] in {"assets", "code"}
        )
    )


def nested_vaults(vault_root: Path) -> tuple[Path, ...]:
    registry_path = vault_root / "projects/repositories.yaml"
    if not registry_path.is_file():
        return ()
    try:
        registry = parse_repository_registry(registry_path.read_text(encoding="utf-8"))
    except (OSError, RepositoryRegistryError):
        return ()
    return tuple(sorted(vault_root / binding.vault for binding in registry.repositories.values()))


def _is_hidden(path: Path) -> bool:
    return path.name.startswith(".") or path.name == "__pycache__"


def owned_directories(vault_root: Path) -> tuple[Path, ...]:
    """Return every visible bundle directory, excluding nested repositories."""
    vault_root = vault_root.absolute()
    if not vault_root.is_dir():
        return ()
    directories: list[Path] = []
    nested = set(nested_vaults(vault_root))
    pending = [vault_root]
    while pending:
        directory = pending.pop()
        directories.append(directory)
        children = [
            child
            for child in directory.iterdir()
            if child.is_dir()
            and not child.is_symlink()
            and not _is_hidden(child)
            and not _is_opaque(vault_root, child)
            and child not in nested
        ]
        pending.extend(sorted(children, reverse=True))
    return tuple(sorted(directories, key=lambda path: path.as_posix()))


def _concept_record(path: Path) -> IndexRecord:
    try:
        metadata = parse_frontmatter(
            path.read_text(encoding="utf-8"),
            source=path,
        ).metadata
    except (OSError, ValueError) as error:
        raise IndexBuildError(f"{path}: {error}") from error

    values: dict[str, str] = {}
    for key in ("type", "title", "description"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value.strip():
            raise IndexBuildError(f"{path}: missing required {key}")
        values[key] = value.strip()
    return IndexRecord(
        section=values["type"],
        title=values["title"],
        link=path.name,
        description=values["description"],
    )


def _directory_description(vault_root: Path, directory: Path) -> str:
    relative = _relative(vault_root, directory).as_posix()
    project_vault = (vault_root / "tasks").is_dir() and not (vault_root / "projects/repositories.yaml").is_file()
    if relative in DIRECTORY_DESCRIPTIONS and not project_vault:
        return DIRECTORY_DESCRIPTIONS[relative]
    parts = Path(relative).parts
    if len(parts) == 1:
        project_descriptions = {
            "assets": "Flat binary evidence for this project.",
            "code": "Ignored in-place VCS working copy.",
            "raw": "Flat immutable source companions for this project.",
            "inbox": "Unprocessed project inputs.",
            "tasks": "Project work state and the single current task.",
            "scratch": "Ephemeral project working notes.",
            "summaries": "Project-specific narrative guides.",
            "concepts": "Project-specific mechanisms and ideas.",
            "entities": "Project-specific named subjects.",
            "playbooks": "Project-specific operational guidance.",
            "comparisons": "Project-specific decision comparisons.",
            "queries": "Project-specific durable answers.",
            "output": "Project deliverables.",
            "examples": "Project examples and fixtures.",
        }
        if parts[0] in project_descriptions:
            return project_descriptions[parts[0]]
    if len(parts) == 3 and parts[0] == "projects":
        descriptions = {
            "assets": "Flat binary evidence for this project.",
            "code": "Ignored in-place VCS working copy.",
            "raw": "Flat immutable source companions for this project.",
            "inbox": "Unprocessed project inputs.",
            "tasks": "Project work state and the single current task.",
            "scratch": "Ephemeral project working notes.",
            "summaries": "Project-specific narrative guides.",
            "concepts": "Project-specific mechanisms and ideas.",
            "entities": "Project-specific named subjects.",
            "playbooks": "Project-specific operational guidance.",
            "comparisons": "Project-specific decision comparisons.",
            "queries": "Project-specific durable answers.",
            "output": "Project deliverables.",
            "examples": "Project examples and fixtures.",
        }
        if parts[2] in descriptions:
            return descriptions[parts[2]]
    label = directory.name.replace("-", " ").replace("_", " ")
    return f"Browse the {label} collection."


def _directory_record(vault_root: Path, directory: Path) -> IndexRecord:
    return IndexRecord(
        section="Subdirectories",
        title=directory.name,
        link=f"{directory.name}/",
        description=_directory_description(vault_root, directory),
    )


def _resource_record(vault_root: Path, path: Path) -> IndexRecord:
    del vault_root
    suffix = path.suffix.lower().lstrip(".") or "file"
    return IndexRecord(
        section="Resources",
        title=path.name,
        link=path.name,
        description=f"Bundled {suffix} resource.",
    )


def child_records(
    directory: Path,
    vault_root: Path,
) -> tuple[IndexRecord, ...]:
    """Describe one directory's immediate visible children."""
    records: list[IndexRecord] = []
    for child in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if _is_hidden(child) or child.name in {INDEX_FILE, LEGACY_INDEX_FILE, LEGACY_LOG_FILE}:
            continue
        if child.is_dir():
            records.append(_directory_record(vault_root, child))
            continue
        if child.name == LOG_FILE:
            records.append(
                IndexRecord(
                    section="Log",
                    title="Bundle history",
                    link=LOG_FILE,
                    description="Newest-first record of material bundle changes.",
                )
            )
            continue
        if child.suffix.lower() == ".md":
            records.append(_concept_record(child))
            continue
        records.append(_resource_record(vault_root, child))
    return tuple(records)


def _section_sort_key(section: str) -> tuple[int, str]:
    if section == "Subdirectories":
        return (0, section)
    if section in {"Resources", "Code Resources", "Log"}:
        return (2, section)
    return (1, section.casefold())


def build_index(
    directory: Path,
    vault_root: Path,
    records: tuple[IndexRecord, ...],
) -> str:
    grouped: dict[str, list[IndexRecord]] = defaultdict(list)
    for record in records:
        grouped[record.section].append(record)

    sections: list[str] = [GENERATED_WARNING]
    if not grouped:
        sections.extend(["# Contents", "", "* No entries yet."])
    else:
        for section in sorted(grouped, key=_section_sort_key):
            sections.extend([f"# {section}", ""])
            for record in sorted(
                grouped[section],
                key=lambda item: (item.title.casefold(), item.link),
            ):
                sections.append(
                    f"* [{record.title}]({record.link}) - {record.description}"
                )
            sections.append("")
        while sections and not sections[-1]:
            sections.pop()

    body = "\n".join(sections) + "\n"
    if directory.absolute() == vault_root.absolute():
        return render_frontmatter({"okf_version": "0.2"}, body)
    return body


def build_indexes(vault_root: Path) -> dict[Path, str]:
    """Render all hierarchical indexes without touching the filesystem."""
    vault_root = vault_root.absolute()
    outputs: dict[Path, str] = {}
    for directory in owned_directories(vault_root):
        records = child_records(directory, vault_root)
        outputs[directory / INDEX_FILE] = build_index(
            directory,
            vault_root,
            records,
        )
    for nested in nested_vaults(vault_root):
        if nested.is_dir():
            outputs.update(build_indexes(nested))
    return outputs


def update_indexes(vault_root: Path, *, check: bool) -> tuple[Path, ...]:
    """Check or write the complete deterministic index set."""
    vault_root = vault_root.absolute()
    outputs = build_indexes(vault_root)
    changed = tuple(
        path
        for path, expected in outputs.items()
        if not path.exists()
        or path.read_text(encoding="utf-8") != expected
    )
    if check:
        return changed
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild hierarchical OKF indexes for an LLM Wiki vault."
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--vault",
        type=Path,
        default=default_vault_root(),
    )
    arguments = parser.parse_args(argv)
    try:
        changed = update_indexes(arguments.vault, check=arguments.check)
    except IndexBuildError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        if changed:
            for path in changed:
                print(f"stale {path.relative_to(arguments.vault.absolute())}")
            return 1
        print("indexes up to date")
        return 0
    if changed:
        for path in changed:
            print(f"updated {path.relative_to(arguments.vault.absolute())}")
    else:
        print("indexes already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
