#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

GENERATED_MARKER = "<!-- generated by the upstream vault initializer; do not edit -->"
HOST_SKILL_ROOTS = (
    Path(".claude/skills"),
    Path(".cursor/skills"),
    Path(".codex/skills"),
)
CURSOR_COMMAND_ROOT = Path(".cursor/commands")
CURSOR_RULE = Path(".cursor/rules/vault-workflow.mdc")
FRONTMATTER_NAME = re.compile(r"^name:\s*(.+)$", re.MULTILINE)
FRONTMATTER_DESCRIPTION = re.compile(r"^description:\s*(.+)$", re.MULTILINE)


def decode_scalar(raw: str) -> str:
    value = raw.strip()
    if value.startswith(('"', "'")):
        try:
            decoded = json.loads(value)
            if isinstance(decoded, str):
                return decoded
        except json.JSONDecodeError:
            return value.strip('"\'')
    return value


def skill_metadata(package: Path) -> tuple[str, str]:
    source = package / "SKILL.md"
    text = source.read_text(encoding="utf-8")
    name_match = FRONTMATTER_NAME.search(text)
    description_match = FRONTMATTER_DESCRIPTION.search(text)
    if not name_match or not description_match:
        raise ValueError(f"skill frontmatter requires name and description: {source}")
    return decode_scalar(name_match.group(1)), decode_scalar(description_match.group(1))


def wrapper_text(root: Path, wrapper: Path, package: Path) -> str:
    name, description = skill_metadata(package)
    canonical = os.path.relpath(package / "SKILL.md", wrapper.parent).replace(os.sep, "/")
    return (
        f"---\nname: {json.dumps(name, ensure_ascii=False)}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
        f"{GENERATED_MARKER}\n\n# {name} adapter\n\n"
        f"Read and follow the canonical skill at [{canonical}]({canonical}) for this request.\n"
        "Resolve scripts, references, and assets relative to that canonical package. "
        "Do not duplicate or modify the skill through this generated adapter.\n"
    )


def cursor_command_text(wrapper: Path, package: Path) -> str:
    name, description = skill_metadata(package)
    canonical = os.path.relpath(package / "SKILL.md", wrapper.parent).replace(os.sep, "/")
    return (
        f"---\ndescription: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
        f"{GENERATED_MARKER}\n\n"
        f"Read and follow [{canonical}]({canonical}) as the complete skill for this request. "
        "Resolve bundled resources from the canonical package and keep host credentials device-local.\n"
    )


def claude_text() -> str:
    return (
        "---\ntype: \"Playbook\"\ntitle: \"Claude Code instruction entrypoint\"\n"
        "description: \"Physical Claude Code adapter for the canonical AGENTS.md workflow.\"\n"
        "status: \"stable\"\nscope: \"vault\"\n"
        "generated: {\"by\":\"process:agent-adapter-renderer\",\"at\":\"1980-01-01T00:00:00Z\"}\n"
        "---\n# Claude Code instructions\n\n"
        f"{GENERATED_MARKER}\n\n"
        "Read and follow [AGENTS.md](./AGENTS.md) before acting. AGENTS.md is the canonical "
        "workflow; this file only provides Claude Code's native physical entrypoint.\n\n"
        "When a nested repository or vault has a nearer AGENTS.md, follow that more specific "
        "contract. Use skills through .claude/skills/ and keep credentials, Cookie files, "
        "generated MCP config, and device-local state outside the repository.\n"
    )


def cursor_rule_text() -> str:
    return (
        "---\ndescription: Load the canonical AGENTS.md workflow before every Cursor agent action.\n"
        "alwaysApply: true\n---\n\n"
        f"{GENERATED_MARKER}\n\n"
        "Read and follow [AGENTS.md](../../AGENTS.md) before acting. If the target has a nearer "
        "nested AGENTS.md, follow that more specific contract. Skills are available through "
        ".cursor/skills/ and explicit .cursor/commands/ adapters.\n"
    )


def replace_generated_file(path: Path, expected: str, *, write: bool) -> bool:
    if path.is_symlink():
        if not write:
            return False
        path.unlink()
    elif path.exists():
        actual = path.read_text(encoding="utf-8")
        if actual == expected:
            return True
        if GENERATED_MARKER not in actual:
            raise ValueError(f"refusing to overwrite non-generated adapter: {path}")
        if not write:
            return False
    elif not write:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    return True


def replace_skill_wrapper(path: Path, expected: str, *, write: bool) -> bool:
    if path.is_symlink():
        if not write:
            return False
        path.unlink()
    elif path.exists() and not path.is_dir():
        raise ValueError(f"skill adapter path is not a directory: {path}")
    wrapper = path / "SKILL.md"
    if path.exists():
        extras = tuple(child for child in path.iterdir() if child.name != "SKILL.md")
        if extras:
            raise ValueError(f"refusing to replace non-wrapper skill directory: {path}")
        if wrapper.exists() and GENERATED_MARKER not in wrapper.read_text(encoding="utf-8"):
            raise ValueError(f"refusing to overwrite customized skill wrapper: {wrapper}")
    elif not write:
        return False
    if not write:
        return wrapper.is_file() and wrapper.read_text(encoding="utf-8") == expected
    path.mkdir(parents=True, exist_ok=True)
    wrapper.write_text(expected, encoding="utf-8", newline="\n")
    return True


def render(root: Path, *, write: bool) -> tuple[Path, ...]:
    root = root.resolve(strict=True)
    canonical = root / ".agents/skills"
    if not canonical.is_dir():
        raise ValueError(f"canonical skill directory is missing: {canonical}")
    packages = tuple(
        path for path in sorted(canonical.iterdir())
        if path.is_dir() and (path / "SKILL.md").is_file()
    )
    if not packages:
        raise ValueError(f"no canonical skills found: {canonical}")
    changed: list[Path] = []
    for host_root in HOST_SKILL_ROOTS:
        for package in packages:
            adapter_dir = root / host_root / package.name
            expected = wrapper_text(root, adapter_dir / "SKILL.md", package)
            if not replace_skill_wrapper(adapter_dir, expected, write=write):
                changed.append(adapter_dir / "SKILL.md")
    for package in packages:
        name, _ = skill_metadata(package)
        command = root / CURSOR_COMMAND_ROOT / f"{name}.md"
        expected = cursor_command_text(command, package)
        if not replace_generated_file(command, expected, write=write):
            changed.append(command)
    for path, expected in (
        (root / "CLAUDE.md", claude_text()),
        (root / CURSOR_RULE, cursor_rule_text()),
    ):
        if not replace_generated_file(path, expected, write=write):
            changed.append(path)
    return tuple(changed)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render portable physical adapters for Claude, Cursor, and Codex.")
    parser.add_argument("--vault", type=Path, default=Path.cwd())
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    try:
        stale = render(arguments.vault, write=arguments.write)
    except (OSError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check and stale:
        for path in stale:
            print(f"stale {path}")
        return 1
    print("agent adapters written" if arguments.write else "agent adapters up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
