import { EditorView } from '@codemirror/view';

const codeBlockCopyTooltipStyles = {
  boxSizing: 'border-box',
  position: 'absolute',
  right: '0',
  bottom: 'calc(100% + 6px)',
  zIndex: '4',
  pointerEvents: 'none',
  whiteSpace: 'nowrap',
  padding: '2px 7px',
  border: '1px solid var(--vscode-editorHoverWidget-border, var(--vscode-contrastBorder, transparent))',
  borderRadius: '4px',
  color: 'var(--vscode-editorHoverWidget-foreground, var(--vscode-editor-foreground))',
  backgroundColor: 'var(--vscode-editorHoverWidget-background, var(--vscode-editor-background))',
  boxShadow: '0 2px 8px color-mix(in srgb, var(--vscode-editor-foreground) 18%, transparent)',
  opacity: '0',
  transform: 'translateY(4px)',
  visibility: 'hidden',
  transition: 'opacity 120ms ease, transform 120ms ease, visibility 0s linear 120ms',
};

const copiedCodeBlockCopyTooltipStyles = {
  opacity: '1',
  transform: 'translateY(0)',
  visibility: 'visible',
  transitionDelay: '0s',
};

const reducedMotionCodeBlockCopyTooltipStyles = {
  transform: 'none',
  transition: 'none',
};

export function hybridStyles() {
  return EditorView.baseTheme({
    '.cm-hybrid-heading-line': {
      fontWeight: '700',
      lineHeight: '1.45',
      paddingTop: '0.25em',
    },
    '.cm-hybrid-heading-line *': {
      textDecoration: 'none',
    },
    '.cm-hybrid-heading-line-1': { fontSize: '1.65em' },
    '.cm-hybrid-heading-line-2': { fontSize: '1.45em' },
    '.cm-hybrid-heading-line-3': { fontSize: '1.3em' },
    '.cm-hybrid-heading-line-4': { fontSize: '1.15em' },
    '.cm-hybrid-heading-line-5': { fontSize: '1.05em' },
    '.cm-hybrid-source-line': {
      fontFamily: 'inherit',
    },
    '.cm-hybrid-document-title': {
      display: 'block',
      padding: '0.28em 0 0.55em',
      border: '0',
      fontFamily: 'var(--vscode-font-family)',
      fontSize: '1.75em',
      fontWeight: '700',
      lineHeight: '1.25',
      color: 'var(--vscode-editor-foreground)',
      backgroundColor: 'transparent',
      outline: 'none',
    },
    '.cm-hybrid-document-title-input': {
      width: '100%',
      borderRadius: '4px',
    },
    '.cm-hybrid-document-title-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-bold': { fontWeight: '700' },
    '.cm-hybrid-italic': { fontStyle: 'italic' },
    '.cm-hybrid-strikethrough': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-highlight': {
      backgroundColor: 'var(--vscode-editor-wordHighlightStrongBackground, rgba(255, 214, 10, 0.22))',
      borderRadius: '4px',
      padding: '0 2px',
    },
    '.cm-hybrid-inline-code': {
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      borderRadius: '4px',
      padding: '1px 5px',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
    },
    '.cm-hybrid-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-inline-math mjx-container': {
      display: 'inline-block',
      height: '1em',
      lineHeight: '1',
      margin: '0 0.08em',
      overflow: 'visible',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
    '.cm-hybrid-inline-html': {
      display: 'inline',
    },
    '.cm-hybrid-inline-html kbd': {
      padding: '1px 4px',
      borderRadius: '3px',
      border: '1px solid var(--vscode-panel-border)',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      fontFamily: 'inherit',
      fontSize: '0.9em',
    },
    '.cm-hybrid-link-text': {
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'transparent',
      borderRadius: '0',
      padding: '0',
      fontWeight: '500',
      textDecoration: 'underline',
      textDecorationThickness: '1.5px',
      textUnderlineOffset: '2px',
    },
    '.cm-hybrid-tag': {
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'var(--vscode-editor-wordHighlightBackground, rgba(64, 128, 255, 0.16))',
      borderRadius: '4px',
      padding: '0 4px',
      fontWeight: '500',
    },
    '.cm-hybrid-blockquote-line': {
      borderLeft: '3px solid var(--vscode-textBlockQuote-border, var(--vscode-textLink-foreground))',
      paddingLeft: '10px',
      color: 'var(--vscode-descriptionForeground)',
      backgroundColor: 'var(--vscode-textBlockQuote-background, transparent)',
    },
    '.cm-hybrid-callout': {
      '--hl-callout-color': 'var(--vscode-charts-blue, var(--vscode-textLink-foreground, var(--vscode-editor-foreground)))',
      display: 'block',
      margin: '0.35em 0 0.9em',
      padding: '10px 14px 12px',
      borderLeft: '0',
      borderRadius: '4px',
      backgroundColor: 'color-mix(in srgb, var(--hl-callout-color) 12%, transparent)',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-callout-note': {
      '--hl-callout-color': 'var(--vscode-charts-blue, var(--vscode-textLink-foreground, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-abstract, .cm-hybrid-callout-summary, .cm-hybrid-callout-tldr, .cm-hybrid-callout-info, .cm-hybrid-callout-todo': {
      '--hl-callout-color': 'var(--vscode-charts-cyan, var(--vscode-textLink-foreground, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-tip, .cm-hybrid-callout-hint, .cm-hybrid-callout-important': {
      '--hl-callout-color': 'var(--vscode-charts-green, var(--vscode-editorInfo-foreground, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-success, .cm-hybrid-callout-check, .cm-hybrid-callout-done': {
      '--hl-callout-color': 'var(--vscode-testing-iconPassed, var(--vscode-charts-green, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-question, .cm-hybrid-callout-help, .cm-hybrid-callout-faq': {
      '--hl-callout-color': 'var(--vscode-charts-yellow, var(--vscode-editorWarning-foreground, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-warning, .cm-hybrid-callout-caution, .cm-hybrid-callout-attention': {
      '--hl-callout-color': 'var(--vscode-editorWarning-foreground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-callout-failure, .cm-hybrid-callout-fail, .cm-hybrid-callout-missing, .cm-hybrid-callout-danger, .cm-hybrid-callout-error, .cm-hybrid-callout-bug': {
      '--hl-callout-color': 'var(--vscode-errorForeground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-callout-example': {
      '--hl-callout-color': 'var(--vscode-charts-purple, var(--vscode-textLink-foreground, var(--vscode-editor-foreground)))',
    },
    '.cm-hybrid-callout-quote, .cm-hybrid-callout-cite': {
      '--hl-callout-color': 'var(--vscode-descriptionForeground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-callout-title': {
      display: 'flex',
      alignItems: 'center',
      gap: '0.4em',
      marginBottom: '0.45em',
      fontWeight: '700',
      color: 'var(--hl-callout-color)',
    },
    '.cm-hybrid-callout-icon': {
      display: 'inline-flex',
      flex: '0 0 auto',
      width: '18px',
      height: '18px',
      color: 'var(--hl-callout-color)',
    },
    '.cm-hybrid-callout-icon svg': {
      width: '18px',
      height: '18px',
      strokeWidth: '2px',
    },
    '.cm-hybrid-callout-fold': {
      appearance: 'none',
      border: '0',
      padding: '0',
      width: '1em',
      height: '1.4em',
      marginLeft: 'auto',
      color: 'var(--hl-callout-color)',
      backgroundColor: 'transparent',
      cursor: 'pointer',
      font: 'inherit',
      lineHeight: '1',
    },
    '.cm-hybrid-callout-body': {
      whiteSpace: 'pre-wrap',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-callout-line': {
      minHeight: '1.4em',
    },
    '.cm-hybrid-callout-task-line, .cm-hybrid-callout-list-line': {
      display: 'flex',
      alignItems: 'baseline',
      gap: '0.45em',
    },
    '.cm-hybrid-callout-task-checkbox': {
      flex: '0 0 auto',
      margin: '0 0.15em 0 0',
      verticalAlign: 'middle',
      cursor: 'pointer',
    },
    '.cm-hybrid-callout-list-marker': {
      flex: '0 0 1.5em',
      color: 'var(--vscode-descriptionForeground)',
      textAlign: 'right',
    },
    '.cm-hybrid-callout-list-content': {
      minWidth: '0',
    },
    '.cm-hybrid-callout-bold': { fontWeight: '700' },
    '.cm-hybrid-callout-italic': { fontStyle: 'italic' },
    '.cm-hybrid-callout-strike': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-callout-highlight': {
      backgroundColor: 'var(--vscode-editor-wordHighlightStrongBackground, rgba(255, 214, 10, 0.22))',
      borderRadius: '4px',
      padding: '0 2px',
      color: 'inherit',
    },
    '.cm-hybrid-callout-link': {
      appearance: 'none',
      border: '0',
      padding: '0',
      margin: '0',
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'transparent',
      font: 'inherit',
      cursor: 'pointer',
      textDecoration: 'underline',
      textDecorationThickness: '1.5px',
      textUnderlineOffset: '2px',
    },
    '.cm-hybrid-callout-link:hover': {
      color: 'var(--vscode-textLink-activeForeground, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-callout-inline-code': {
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      borderRadius: '4px',
      padding: '1px 5px',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
    },
    '.cm-hybrid-callout-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-callout-inline-math mjx-container': {
      display: 'inline-block',
      height: '1em',
      lineHeight: '1',
      margin: '0 0.08em',
      overflow: 'visible',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-callout-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
    '.cm-hybrid-list-line': { paddingBottom: '1px' },
    '.cm-hybrid-task-checkbox': {
      marginRight: '7px',
      verticalAlign: 'middle',
      accentColor: 'var(--vscode-textLink-foreground)',
    },
    '.cm-hybrid-properties': {
      display: 'block',
      padding: '0.35em 0 1.1em',
      color: 'var(--vscode-editor-foreground)',
      fontFamily: 'inherit',
      fontSize: '1em',
      lineHeight: 'inherit',
    },
    '.cm-hybrid-properties-heading': {
      appearance: 'none',
      display: 'flex',
      alignItems: 'center',
      gap: '0.3em',
      width: '100%',
      marginBottom: '0.35em',
      border: '0',
      padding: '0',
      backgroundColor: 'transparent',
      font: 'inherit',
      fontWeight: '600',
      color: 'var(--vscode-editor-foreground)',
      textAlign: 'left',
      cursor: 'pointer',
    },
    '.cm-hybrid-properties-chevron': {
      display: 'inline-flex',
      width: '1em',
      color: 'var(--vscode-descriptionForeground)',
      justifyContent: 'center',
    },
    '.cm-hybrid-properties-rows': {
      display: 'grid',
      gap: '0.15em',
      maxWidth: '36rem',
    },
    '.cm-hybrid-property-row': {
      display: 'grid',
      gridTemplateColumns: 'minmax(9rem, 0.36fr) 1fr',
      gap: '1rem',
      alignItems: 'center',
      minHeight: '1.65em',
    },
    '.cm-hybrid-property-name': {
      color: 'var(--vscode-descriptionForeground)',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.cm-hybrid-property-name-cell': {
      display: 'flex',
      alignItems: 'center',
      gap: '0.35em',
      minWidth: '0',
    },
    '.cm-hybrid-property-icon': {
      display: 'inline-flex',
      flex: '0 0 1.05em',
      width: '1.05em',
      height: '1.05em',
      alignItems: 'center',
      justifyContent: 'center',
      color: 'var(--vscode-descriptionForeground)',
    },
    '.cm-hybrid-property-icon svg': {
      width: '100%',
      height: '100%',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '1.7',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    '.cm-hybrid-property-name-input': {
      flex: '1 1 auto',
      minWidth: '0',
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-name-input:focus': {
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-value': {
      minWidth: '0',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-property-chip-display, .cm-hybrid-property-scalar-display': {
      appearance: 'none',
      maxWidth: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'inherit',
      backgroundColor: 'transparent',
      font: 'inherit',
      textAlign: 'left',
      cursor: 'text',
    },
    '.cm-hybrid-property-chip-display:hover, .cm-hybrid-property-scalar-display:hover': {
      backgroundColor: 'color-mix(in srgb, var(--vscode-editor-foreground) 6%, transparent)',
    },
    '.cm-hybrid-properties-rows[hidden], .cm-hybrid-property-list-input[hidden], .cm-hybrid-property-value-input[hidden], .cm-hybrid-property-chip-display[hidden], .cm-hybrid-property-scalar-display[hidden]': {
      display: 'none',
    },
    '.cm-hybrid-property-value-input': {
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-value-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-list-input': {
      minWidth: '11rem',
      maxWidth: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-list-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-chip-shell': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.18em',
      marginRight: '0.35em',
      padding: '0 0.2em 0 0.45em',
      borderRadius: '999px',
      backgroundColor: 'var(--vscode-badge-background, rgba(127,127,127,.2))',
      color: 'var(--vscode-badge-foreground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-property-chip-remove': {
      display: 'inline-flex',
      width: '1em',
      height: '1em',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: '50%',
      color: 'inherit',
      cursor: 'pointer',
      opacity: '0.62',
      lineHeight: '1',
    },
    '.cm-hybrid-property-chip-remove:hover, .cm-hybrid-property-chip-remove:focus': {
      backgroundColor: 'color-mix(in srgb, currentColor 14%, transparent)',
      opacity: '1',
      outline: 'none',
    },
    '.cm-hybrid-property-add': {
      marginTop: '0.15em',
      padding: '0',
      border: '0',
      backgroundColor: 'transparent',
      color: 'var(--vscode-descriptionForeground)',
      font: 'inherit',
      textAlign: 'left',
      cursor: 'pointer',
    },
    '.cm-hybrid-new-property-name-input, .cm-hybrid-new-property-value-input': {
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-new-property-name-input:focus, .cm-hybrid-new-property-value-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-bullet': {
      color: 'var(--vscode-descriptionForeground)',
      display: 'inline-block',
      width: '1em',
      marginRight: '5px',
      textAlign: 'center',
    },
    '.cm-hybrid-number': {
      color: 'var(--vscode-descriptionForeground)',
      display: 'inline-block',
      marginRight: '5px',
      fontWeight: '600',
    },
    '.cm-hybrid-image-img': {
      maxWidth: '100%',
      maxHeight: '260px',
      borderRadius: '4px',
      border: '1px solid var(--vscode-panel-border)',
      display: 'block',
    },
    '.cm-hybrid-image-fallback': {
      color: 'var(--vscode-descriptionForeground)',
      fontStyle: 'italic',
    },
    '.cm-hybrid-math-block': {
      display: 'block',
      padding: '0.65em 0 0.9em',
    },
    '.cm-hybrid-math-block-line-preview': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      height: '1lh',
      padding: '0',
      verticalAlign: 'top',
    },
    '.cm-line:has(.cm-hybrid-math-block) > .cm-widgetBuffer': {
      display: 'none',
    },
    '.cm-hybrid-math-block-inner': {
      boxSizing: 'border-box',
      padding: '0',
      border: '1px solid transparent',
      borderRadius: '4px',
      backgroundColor: 'transparent',
      overflowX: 'auto',
      textAlign: 'center',
    },
    '.cm-hybrid-math-block-inner:hover, .cm-hybrid-math-block-inner:focus-within': {
      borderColor: 'var(--vscode-panel-border, rgba(127,127,127,.35))',
    },
    '.cm-hybrid-math-block mjx-container[display="true"]': {
      margin: '0',
    },
    '.cm-hybrid-math-block mjx-container': {
      fontSize: '1.06em',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-math-block-line-preview mjx-container': {
      fontSize: '0.94em',
      lineHeight: '1',
    },
    '.cm-hybrid-math-block mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-math-block-line-preview mjx-container[jax="SVG"] > svg': {
      maxHeight: '1.12em',
    },
    '.cm-hybrid-math-error': {
      boxSizing: 'border-box',
      maxWidth: '100%',
      border: '1px solid var(--vscode-inputValidation-errorBorder, var(--vscode-errorForeground, #f48771))',
      borderRadius: '4px',
      backgroundColor: 'var(--vscode-inputValidation-errorBackground, rgba(244, 135, 113, 0.10))',
      color: 'var(--vscode-editor-foreground)',
      boxShadow: 'inset 3px 0 0 var(--vscode-errorForeground, #f48771)',
    },
    '.cm-hybrid-math-error-display': {
      display: 'grid',
      gridTemplateColumns: 'auto minmax(0, 1fr)',
      columnGap: '8px',
      rowGap: '4px',
      margin: '0 auto',
      padding: '8px 10px 8px 12px',
      textAlign: 'left',
    },
    '.cm-hybrid-math-error-inline': {
      display: 'inline-grid',
      gridTemplateColumns: 'auto minmax(0, max-content)',
      gap: '2px 6px',
      padding: '1px 5px 1px 7px',
      verticalAlign: 'baseline',
      boxShadow: 'inset 2px 0 0 var(--vscode-errorForeground, #f48771)',
    },
    '.cm-hybrid-math-error-title': {
      color: 'var(--vscode-errorForeground, var(--vscode-editor-foreground))',
      fontWeight: '700',
      whiteSpace: 'nowrap',
    },
    '.cm-hybrid-math-error-title::before': {
      content: '"fx"',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: '18px',
      height: '16px',
      marginRight: '6px',
      borderRadius: '3px',
      backgroundColor: 'rgba(244, 135, 113, 0.16)',
      color: 'var(--vscode-errorForeground, var(--vscode-editor-foreground))',
      fontSize: '10px',
      fontWeight: '700',
      lineHeight: '1',
    },
    '.cm-hybrid-math-error-message': {
      minWidth: '0',
      overflow: 'hidden',
      color: 'var(--vscode-descriptionForeground, var(--vscode-editor-foreground))',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.cm-hybrid-math-error-source': {
      gridColumn: '1 / -1',
      minWidth: '0',
      overflow: 'hidden',
      borderRadius: '3px',
      padding: '2px 4px',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127, 127, 127, 0.16))',
      color: 'var(--vscode-textPreformat-foreground, var(--vscode-editor-foreground))',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
      fontSize: '0.92em',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.cm-hybrid-hidden-source': {
      display: 'inline',
      lineHeight: 'inherit',
      visibility: 'hidden',
      whiteSpace: 'pre',
    },
    '.cm-hybrid-math-delimiter': {
      color: 'var(--vscode-symbolIcon-operatorForeground, var(--vscode-editor-foreground))',
      fontWeight: '600',
    },
    '.cm-hybrid-math-source': {
      color: 'var(--vscode-symbolIcon-variableForeground, var(--vscode-editor-foreground))',
      fontStyle: 'italic',
    },
    '.cm-hybrid-mermaid-block': {
      display: 'block',
      boxSizing: 'border-box',
      outlineStyle: 'solid',
      outlineWidth: '1px',
      outlineColor: 'rgba(0, 0, 0, 0)',
      outlineOffset: '-1px',
      padding: '0.65em 0',
      color: 'var(--vscode-editor-foreground)',
      boxShadow: '0 0 0 1px transparent, 0 0 0 transparent',
      transition: 'outline-color 120ms ease, box-shadow 120ms ease',
    },
    '.cm-hybrid-mermaid-block:hover, .cm-hybrid-mermaid-block:focus, .cm-hybrid-mermaid-block:focus-within': {
      outlineColor: 'rgba(142, 120, 255, 0.65)',
      boxShadow: '0 0 0 1px rgba(142, 120, 255, 0.16), 0 0 10px rgba(142, 120, 255, 0.22)',
    },
    '.cm-hybrid-mermaid-toolbar': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: '4px',
      marginBottom: '4px',
      userSelect: 'none',
    },
    '.cm-hybrid-mermaid-edit-source': {
      width: '30px',
      height: '24px',
      border: '1px solid var(--vscode-panel-border)',
      borderRadius: '4px',
      padding: '0',
      backgroundColor: 'var(--vscode-button-secondaryBackground)',
      color: 'var(--vscode-button-secondaryForeground)',
      font: '600 11px var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
      lineHeight: '1',
      cursor: 'pointer',
      opacity: '0',
      transition: 'opacity 120ms ease',
    },
    '.cm-hybrid-mermaid-block:hover .cm-hybrid-mermaid-edit-source, .cm-hybrid-mermaid-block:focus .cm-hybrid-mermaid-edit-source, .cm-hybrid-mermaid-block:focus-within .cm-hybrid-mermaid-edit-source': {
      opacity: '1',
    },
    '.cm-hybrid-mermaid-edit-source:hover': {
      backgroundColor: 'var(--vscode-toolbar-hoverBackground, var(--vscode-button-background))',
      color: 'var(--vscode-button-foreground)',
    },
    '.cm-hybrid-mermaid-block-inner': {
      display: 'block',
      boxSizing: 'border-box',
      maxWidth: '100%',
      maxHeight: 'min(70vh, 720px)',
      overflow: 'auto',
      padding: '0.35em 0',
      textAlign: 'center',
      scrollbarGutter: 'stable both-edges',
    },
    '.cm-hybrid-mermaid-block svg': {
      display: 'inline-block',
      maxWidth: 'none',
      height: 'auto',
    },
    '.cm-hybrid-mermaid-error': {
      margin: '0',
      color: 'var(--vscode-errorForeground, var(--vscode-editor-foreground))',
      whiteSpace: 'pre-wrap',
    },
    '&': {
      '--hl-codeblock-background': 'var(--vscode-textCodeBlock-background, rgba(127, 127, 127, 0.10))',
      '--hl-code-token-comment': 'var(--vscode-descriptionForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-keyword': 'var(--vscode-symbolIcon-keywordForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-string': 'var(--vscode-symbolIcon-stringForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-function': 'var(--vscode-symbolIcon-functionForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-number': 'var(--vscode-symbolIcon-numberForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-boolean': 'var(--vscode-symbolIcon-booleanForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-operator': 'var(--vscode-symbolIcon-operatorForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-punctuation': 'var(--vscode-descriptionForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-type': 'var(--vscode-symbolIcon-classForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-namespace': 'var(--vscode-symbolIcon-namespaceForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-property': 'var(--vscode-symbolIcon-propertyForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-variable': 'var(--vscode-symbolIcon-variableForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-regex': 'var(--vscode-symbolIcon-stringForeground, var(--vscode-editor-foreground))',
      '--hl-code-token-tag': 'var(--vscode-symbolIcon-keywordForeground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-codeblock': {
      display: 'block',
      height: '1lh',
      marginLeft: '-6px',
      marginRight: '-2px',
      overflow: 'visible',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
      fontSize: '1em',
      fontWeight: 'normal',
      lineHeight: 'inherit',
    },
    '.cm-line:has(.cm-hybrid-codeblock) > .cm-widgetBuffer, .cm-line:has(.cm-hybrid-codeblock-footer) > .cm-widgetBuffer': {
      display: 'none',
    },
    '.cm-hybrid-codeblock-inner': {
      boxSizing: 'border-box',
      height: '1lh',
      borderTopLeftRadius: '4px',
      borderTopRightRadius: '4px',
      backgroundColor: 'var(--hl-codeblock-background)',
      overflow: 'visible',
    },
    '.cm-hybrid-codeblock-header': {
      boxSizing: 'border-box',
      position: 'relative',
      display: 'flex',
      alignItems: 'center',
      height: '1lh',
      lineHeight: 'inherit',
      padding: '0 38px 0 14px',
      backgroundColor: 'var(--hl-codeblock-background)',
    },
    '.cm-hybrid-codeblock-language': {
      color: 'var(--vscode-descriptionForeground)',
      fontFamily: 'inherit',
      fontSize: 'inherit',
      fontWeight: 'normal',
      lineHeight: 'inherit',
      letterSpacing: '0',
    },
    '.cm-hybrid-codeblock-copy': {
      position: 'absolute',
      top: '50%',
      right: '8px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '20px',
      transform: 'translateY(-50%)',
      border: '0',
      borderRadius: '3px',
      padding: '0',
      color: 'var(--vscode-descriptionForeground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      cursor: 'pointer',
      opacity: '0.72',
    },
    '.cm-hybrid-codeblock-copy-icon': {
      width: '16px',
      height: '16px',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '1.25',
    },
    '.cm-hybrid-codeblock-copy-tooltip': codeBlockCopyTooltipStyles,
    '.cm-hybrid-codeblock-copy.is-copied .cm-hybrid-codeblock-copy-tooltip': copiedCodeBlockCopyTooltipStyles,
    '.cm-hybrid-codeblock-copy.cm-hybrid-codeblock-copy-reduced-motion .cm-hybrid-codeblock-copy-tooltip': reducedMotionCodeBlockCopyTooltipStyles,
    '.cm-hybrid-codeblock:hover .cm-hybrid-codeblock-copy, .cm-hybrid-codeblock:focus-within .cm-hybrid-codeblock-copy, .cm-hybrid-codeblock-copy:focus-visible': {
      opacity: '1',
    },
    '.cm-hybrid-codeblock-copy:hover': {
      color: 'var(--vscode-editor-foreground)',
      backgroundColor: 'color-mix(in srgb, var(--vscode-editor-foreground) 10%, transparent)',
    },
    '.cm-hybrid-codeblock-content-line': {
      boxSizing: 'border-box',
      paddingLeft: '14px',
      paddingRight: '14px',
      backgroundColor: 'var(--hl-codeblock-background)',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
      fontSize: '1em',
      lineHeight: 'inherit',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-codeblock-active-opening-line, .cm-hybrid-codeblock-active-closing-line': {
      boxSizing: 'border-box',
      paddingLeft: '14px',
      paddingRight: '14px',
      backgroundColor: 'var(--hl-codeblock-background)',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
      fontSize: '1em',
      lineHeight: 'inherit',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-codeblock-active-opening-line': {
      borderTopLeftRadius: '4px',
      borderTopRightRadius: '4px',
    },
    '.cm-hybrid-codeblock-active-closing-line': {
      borderBottomLeftRadius: '4px',
      borderBottomRightRadius: '4px',
    },
    '.vscode-high-contrast & .cm-hybrid-codeblock-inner, .vscode-high-contrast & .cm-hybrid-codeblock-active-opening-line, .vscode-high-contrast-light & .cm-hybrid-codeblock-inner, .vscode-high-contrast-light & .cm-hybrid-codeblock-active-opening-line': {
      boxShadow: 'inset 1px 0 var(--vscode-contrastBorder), inset -1px 0 var(--vscode-contrastBorder), inset 0 1px var(--vscode-contrastBorder)',
    },
    '.vscode-high-contrast & .cm-hybrid-codeblock-content-line, .vscode-high-contrast-light & .cm-hybrid-codeblock-content-line': {
      boxShadow: 'inset 1px 0 var(--vscode-contrastBorder), inset -1px 0 var(--vscode-contrastBorder)',
    },
    '.vscode-high-contrast & .cm-hybrid-codeblock-footer, .vscode-high-contrast & .cm-hybrid-codeblock-active-closing-line, .vscode-high-contrast-light & .cm-hybrid-codeblock-footer, .vscode-high-contrast-light & .cm-hybrid-codeblock-active-closing-line': {
      boxShadow: 'inset 1px 0 var(--vscode-contrastBorder), inset -1px 0 var(--vscode-contrastBorder), inset 0 -1px var(--vscode-contrastBorder)',
    },
    '.cm-hybrid-prism-token.token.comment, .cm-hybrid-prism-token.token.prolog, .cm-hybrid-prism-token.token.doctype, .cm-hybrid-prism-token.token.cdata': {
      color: 'var(--hl-code-token-comment)',
    },
    '.cm-hybrid-prism-token.token.keyword, .cm-hybrid-prism-token.token.atrule': {
      color: 'var(--hl-code-token-keyword)',
    },
    '.cm-hybrid-prism-token.token.string, .cm-hybrid-prism-token.token.char, .cm-hybrid-prism-token.token.attr-value, .cm-hybrid-prism-token.token.url': {
      color: 'var(--hl-code-token-string)',
    },
    '.cm-hybrid-prism-token.token.function, .cm-hybrid-prism-token.token.method': {
      color: 'var(--hl-code-token-function)',
    },
    '.cm-hybrid-prism-token.token.number, .cm-hybrid-prism-token.token.constant': {
      color: 'var(--hl-code-token-number)',
    },
    '.cm-hybrid-prism-token.token.boolean': {
      color: 'var(--hl-code-token-boolean)',
    },
    '.cm-hybrid-prism-token.token.operator': {
      color: 'var(--hl-code-token-operator)',
    },
    '.cm-hybrid-prism-token.token.punctuation': {
      color: 'var(--hl-code-token-punctuation)',
    },
    '.cm-hybrid-prism-token.token.class-name, .cm-hybrid-prism-token.token.builtin': {
      color: 'var(--hl-code-token-type)',
    },
    '.cm-hybrid-prism-token.token.namespace': {
      color: 'var(--hl-code-token-namespace)',
    },
    '.cm-hybrid-prism-token.token.property, .cm-hybrid-prism-token.token.attr-name, .cm-hybrid-prism-token.token.selector': {
      color: 'var(--hl-code-token-property)',
    },
    '.cm-hybrid-prism-token.token.variable, .cm-hybrid-prism-token.token.parameter': {
      color: 'var(--hl-code-token-variable)',
    },
    '.cm-hybrid-prism-token.token.regex': {
      color: 'var(--hl-code-token-regex)',
    },
    '.cm-hybrid-prism-token.token.tag': {
      color: 'var(--hl-code-token-tag)',
    },
    '.cm-hybrid-codeblock-content-line *': {
      color: 'inherit',
    },
    '.cm-hybrid-prism-token.token.important, .cm-hybrid-prism-token.token.bold': {
      fontWeight: '600',
    },
    '.cm-hybrid-prism-token.token.italic': {
      fontStyle: 'italic',
    },
    '.cm-hybrid-codeblock-footer': {
      display: 'block',
      boxSizing: 'border-box',
      height: '1lh',
      marginLeft: '-6px',
      marginRight: '-2px',
      overflow: 'hidden',
      fontSize: '1em',
      lineHeight: 'inherit',
      borderBottomLeftRadius: '4px',
      borderBottomRightRadius: '4px',
      backgroundColor: 'var(--hl-codeblock-background)',
    },
    '.cm-hybrid-footnote-ref': {
      color: 'var(--vscode-textLink-foreground)',
      fontSize: '0.78em',
      verticalAlign: 'super',
      lineHeight: '0',
      fontWeight: '600',
    },
    '.cm-hybrid-footnote-def-label': {
      color: 'var(--vscode-textLink-foreground)',
      fontSize: '0.85em',
      verticalAlign: 'super',
      lineHeight: '0',
      fontWeight: '600',
    },
    '.cm-hybrid-footnote-def-separator': {
      color: 'var(--vscode-descriptionForeground)',
      fontSize: '0.85em',
      verticalAlign: 'super',
      lineHeight: '0',
      marginRight: '0.2em',
    },
    '.cm-hybrid-hr': {
      borderBottom: '1px solid var(--vscode-panel-border)',
      height: '0',
      margin: '0.75em 0',
    },
    '.cm-hybrid-table-widget': {
      display: 'block',
      padding: '0.45em 0 0.8em',
    },
    '.cm-hybrid-table-widget-inner': {
      display: 'block',
      overflowX: 'auto',
    },
    '.cm-hybrid-table': {
      borderCollapse: 'collapse',
      width: 'max-content',
      minWidth: 'min(100%, 28rem)',
      maxWidth: '100%',
      fontFamily: 'inherit',
      fontSize: '1em',
    },
    '.cm-hybrid-table th, .cm-hybrid-table td': {
      border: '1px solid var(--vscode-panel-border)',
      minWidth: '10ch',
      padding: '5px 9px',
      textAlign: 'left',
      verticalAlign: 'top',
      whiteSpace: 'pre-wrap',
    },
    '.cm-hybrid-table th': {
      fontWeight: '600',
      backgroundColor: 'var(--vscode-editor-lineHighlightBackground, rgba(127,127,127,.12))',
    },
    '.cm-hybrid-table-cell-display': {
      display: 'block',
      minHeight: '1lh',
      cursor: 'text',
    },
    '.cm-hybrid-table-cell-display[hidden], .cm-hybrid-table-cell-input[hidden]': {
      display: 'none',
    },
    '.cm-hybrid-table-cell-input': {
      boxSizing: 'border-box',
      width: '100%',
      minWidth: '8ch',
      margin: '0',
      padding: '0',
      border: '0',
      borderRadius: '2px',
      outline: 'none',
      backgroundColor: 'transparent',
      color: 'inherit',
      font: 'inherit',
      lineHeight: 'inherit',
    },
    '.cm-hybrid-table-cell-input:focus': {
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
      backgroundColor: 'var(--vscode-input-background, transparent)',
    },
    '.cm-hybrid-table-bold': { fontWeight: '700' },
    '.cm-hybrid-table-italic': { fontStyle: 'italic' },
    '.cm-hybrid-table-strike': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-table-highlight': {
      backgroundColor: 'color-mix(in srgb, var(--vscode-editor-findMatchHighlightBackground, #ffd33d) 38%, transparent)',
      borderRadius: '2px',
      padding: '0 2px',
    },
    '.cm-hybrid-table-link': {
      appearance: 'none',
      border: '0',
      padding: '0',
      color: 'var(--vscode-textLink-foreground)',
      background: 'transparent',
      font: 'inherit',
      textDecoration: 'underline',
      cursor: 'pointer',
    },
    '.cm-hybrid-table-link:hover': {
      color: 'var(--vscode-textLink-activeForeground, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-table-inline-code': {
      padding: '0.05em 0.28em',
      borderRadius: '3px',
      backgroundColor: 'var(--vscode-textCodeBlock-background)',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--hl-editor-font-family, var(--vscode-editor-font-family, ui-monospace, Menlo, monospace))',
    },
    '.cm-hybrid-table-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-table-inline-math mjx-container': {
      display: 'inline-block',
      height: '1em',
      lineHeight: '1',
      margin: '0 0.08em',
      overflow: 'visible',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-table-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
  });
}
