import { EditorView } from '@codemirror/view';

export function hybridStyles() {
  return EditorView.baseTheme({
    '.cm-hybrid-heading-line': {
      fontWeight: '700',
      lineHeight: '1.45',
      paddingTop: '0.25em',
    },
    '.cm-hybrid-heading-line *': {
      textDecoration: 'none',
    },
    '.cm-hybrid-heading-line-1': { fontSize: '1.45em' },
    '.cm-hybrid-heading-line-2': { fontSize: '1.3em' },
    '.cm-hybrid-heading-line-3': { fontSize: '1.18em' },
    '.cm-hybrid-heading-line-4': { fontSize: '1.08em' },
    '.cm-hybrid-heading-line-5': { fontSize: '1.02em' },
    '.cm-hybrid-document-title': {
      display: 'block',
      padding: '0.28em 0 0.55em',
      border: '0',
      fontFamily: 'var(--vscode-font-family)',
      fontSize: '1.75em',
      fontWeight: '700',
      lineHeight: '1.25',
      color: 'var(--vscode-editor-foreground)',
      backgroundColor: 'transparent',
      outline: 'none',
    },
    '.cm-hybrid-document-title-input': {
      width: '100%',
      borderRadius: '4px',
    },
    '.cm-hybrid-document-title-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-bold': { fontWeight: '700' },
    '.cm-hybrid-italic': { fontStyle: 'italic' },
    '.cm-hybrid-strikethrough': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-highlight': {
      backgroundColor: 'var(--vscode-editor-wordHighlightStrongBackground, rgba(255, 214, 10, 0.22))',
      borderRadius: '4px',
      padding: '0 2px',
    },
    '.cm-hybrid-inline-code': {
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      borderRadius: '4px',
      padding: '1px 5px',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
    },
    '.cm-hybrid-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-inline-math mjx-container': {
      display: 'inline-block',
      margin: '0 0.08em',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
    '.cm-hybrid-inline-html': {
      display: 'inline',
    },
    '.cm-hybrid-inline-html kbd': {
      padding: '1px 4px',
      borderRadius: '3px',
      border: '1px solid var(--vscode-panel-border)',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
      fontSize: '0.9em',
    },
    '.cm-hybrid-link-text': {
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'transparent',
      borderRadius: '0',
      padding: '0',
      fontWeight: '500',
      textDecoration: 'underline',
      textDecorationThickness: '1.5px',
      textUnderlineOffset: '2px',
    },
    '.cm-hybrid-tag': {
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'var(--vscode-editor-wordHighlightBackground, rgba(64, 128, 255, 0.16))',
      borderRadius: '4px',
      padding: '0 4px',
      fontWeight: '500',
    },
    '.cm-hybrid-blockquote-line': {
      borderLeft: '3px solid var(--vscode-textBlockQuote-border, var(--vscode-textLink-foreground))',
      paddingLeft: '10px',
      color: 'var(--vscode-descriptionForeground)',
      backgroundColor: 'var(--vscode-textBlockQuote-background, transparent)',
    },
    '.cm-hybrid-callout': {
      display: 'block',
      margin: '0.35em 0 0.9em',
      padding: '8px 12px 10px',
      borderLeft: '4px solid var(--vscode-textLink-foreground)',
      borderRadius: '4px',
      backgroundColor: 'var(--vscode-textBlockQuote-background, rgba(127,127,127,.1))',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-callout-title': {
      display: 'flex',
      alignItems: 'center',
      gap: '0.35em',
      marginBottom: '0.35em',
      fontWeight: '700',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-callout-fold': {
      appearance: 'none',
      border: '0',
      padding: '0',
      width: '1em',
      height: '1.4em',
      color: 'var(--vscode-icon-foreground)',
      backgroundColor: 'transparent',
      cursor: 'pointer',
      font: 'inherit',
      lineHeight: '1',
    },
    '.cm-hybrid-callout-body': {
      whiteSpace: 'pre-wrap',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-callout-line': {
      minHeight: '1.4em',
    },
    '.cm-hybrid-callout-task-line, .cm-hybrid-callout-list-line': {
      display: 'flex',
      alignItems: 'baseline',
      gap: '0.45em',
    },
    '.cm-hybrid-callout-task-checkbox': {
      flex: '0 0 auto',
      margin: '0 0.15em 0 0',
      verticalAlign: 'middle',
      cursor: 'pointer',
    },
    '.cm-hybrid-callout-list-marker': {
      flex: '0 0 1.5em',
      color: 'var(--vscode-descriptionForeground)',
      textAlign: 'right',
    },
    '.cm-hybrid-callout-list-content': {
      minWidth: '0',
    },
    '.cm-hybrid-callout-bold': { fontWeight: '700' },
    '.cm-hybrid-callout-italic': { fontStyle: 'italic' },
    '.cm-hybrid-callout-strike': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-callout-highlight': {
      backgroundColor: 'var(--vscode-editor-wordHighlightStrongBackground, rgba(255, 214, 10, 0.22))',
      borderRadius: '4px',
      padding: '0 2px',
      color: 'inherit',
    },
    '.cm-hybrid-callout-link': {
      appearance: 'none',
      border: '0',
      padding: '0',
      margin: '0',
      color: 'var(--vscode-textLink-foreground)',
      backgroundColor: 'transparent',
      font: 'inherit',
      cursor: 'pointer',
      textDecoration: 'underline',
      textDecorationThickness: '1.5px',
      textUnderlineOffset: '2px',
    },
    '.cm-hybrid-callout-link:hover': {
      color: 'var(--vscode-textLink-activeForeground, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-callout-inline-code': {
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.18))',
      borderRadius: '4px',
      padding: '1px 5px',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
    },
    '.cm-hybrid-callout-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-callout-inline-math mjx-container': {
      display: 'inline-block',
      margin: '0 0.08em',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-callout-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
    '.cm-hybrid-list-line': { paddingBottom: '1px' },
    '.cm-hybrid-task-checkbox': {
      marginRight: '7px',
      verticalAlign: 'middle',
      accentColor: 'var(--vscode-textLink-foreground)',
    },
    '.cm-hybrid-properties': {
      display: 'block',
      padding: '0.35em 0 1.1em',
      color: 'var(--vscode-editor-foreground)',
      fontFamily: 'var(--vscode-font-family)',
      fontSize: 'var(--vscode-font-size)',
      lineHeight: '1.6',
    },
    '.cm-hybrid-properties-heading': {
      marginBottom: '0.35em',
      fontWeight: '600',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-properties-rows': {
      display: 'grid',
      gap: '0.15em',
      maxWidth: '36rem',
    },
    '.cm-hybrid-property-row': {
      display: 'grid',
      gridTemplateColumns: 'minmax(9rem, 0.36fr) 1fr',
      gap: '1rem',
      alignItems: 'center',
      minHeight: '1.65em',
    },
    '.cm-hybrid-property-name': {
      color: 'var(--vscode-descriptionForeground)',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.cm-hybrid-property-name-input': {
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-name-input:focus': {
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-value': {
      minWidth: '0',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-property-value-input': {
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-value-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-list-input': {
      minWidth: '11rem',
      maxWidth: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-property-list-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-property-chip': {
      display: 'inline-block',
      marginRight: '0.35em',
      padding: '0 0.45em',
      borderRadius: '999px',
      backgroundColor: 'var(--vscode-badge-background, rgba(127,127,127,.2))',
      color: 'var(--vscode-badge-foreground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-property-add': {
      marginTop: '0.15em',
      padding: '0',
      border: '0',
      backgroundColor: 'transparent',
      color: 'var(--vscode-descriptionForeground)',
      font: 'inherit',
      textAlign: 'left',
      cursor: 'pointer',
    },
    '.cm-hybrid-new-property-name-input, .cm-hybrid-new-property-value-input': {
      width: '100%',
      border: '0',
      borderRadius: '4px',
      padding: '2px 4px',
      color: 'var(--vscode-input-foreground, var(--vscode-editor-foreground))',
      backgroundColor: 'transparent',
      font: 'inherit',
      outline: 'none',
    },
    '.cm-hybrid-new-property-name-input:focus, .cm-hybrid-new-property-value-input:focus': {
      backgroundColor: 'var(--vscode-input-background, color-mix(in srgb, var(--vscode-editor-foreground) 8%, transparent))',
      boxShadow: '0 0 0 1px var(--vscode-focusBorder, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-bullet': {
      color: 'var(--vscode-descriptionForeground)',
      display: 'inline-block',
      width: '1em',
      marginRight: '5px',
      textAlign: 'center',
    },
    '.cm-hybrid-number': {
      color: 'var(--vscode-descriptionForeground)',
      display: 'inline-block',
      marginRight: '5px',
      fontWeight: '600',
    },
    '.cm-hybrid-image-img': {
      maxWidth: '100%',
      maxHeight: '260px',
      borderRadius: '4px',
      border: '1px solid var(--vscode-panel-border)',
      display: 'block',
    },
    '.cm-hybrid-image-fallback': {
      color: 'var(--vscode-descriptionForeground)',
      fontStyle: 'italic',
    },
    '.cm-hybrid-math-block': {
      display: 'block',
      padding: '0.65em 0 0.9em',
    },
    '.cm-hybrid-math-block-line-preview': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      height: '1lh',
      padding: '0',
      verticalAlign: 'top',
    },
    '.cm-line:has(.cm-hybrid-math-block) > .cm-widgetBuffer': {
      display: 'none',
    },
    '.cm-hybrid-math-block-inner': {
      padding: '0',
      border: '0',
      backgroundColor: 'transparent',
      overflowX: 'auto',
      textAlign: 'center',
    },
    '.cm-hybrid-math-block mjx-container[display="true"]': {
      margin: '0',
    },
    '.cm-hybrid-math-block mjx-container': {
      fontSize: '1.06em',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-math-block-line-preview mjx-container': {
      fontSize: '0.94em',
      lineHeight: '1',
    },
    '.cm-hybrid-math-block mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-math-block-line-preview mjx-container[jax="SVG"] > svg': {
      maxHeight: '1.12em',
    },
    '.cm-hybrid-hidden-source': {
      display: 'inline',
      lineHeight: 'inherit',
      visibility: 'hidden',
      whiteSpace: 'pre',
    },
    '.cm-hybrid-math-delimiter': {
      color: 'var(--vscode-symbolIcon-operatorForeground, #c586c0)',
      fontWeight: '600',
    },
    '.cm-hybrid-math-source': {
      color: 'var(--vscode-symbolIcon-variableForeground, #4ec9b0)',
      fontStyle: 'italic',
    },
    '.cm-hybrid-mermaid-block': {
      display: 'block',
      boxSizing: 'border-box',
      padding: '0.65em 0',
      color: 'var(--vscode-editor-foreground)',
    },
    '.cm-hybrid-mermaid-block-inner': {
      display: 'block',
      boxSizing: 'border-box',
      maxWidth: '100%',
      maxHeight: 'min(70vh, 720px)',
      overflow: 'auto',
      padding: '0.35em 0',
      textAlign: 'center',
      scrollbarGutter: 'stable both-edges',
    },
    '.cm-hybrid-mermaid-block svg': {
      display: 'inline-block',
      maxWidth: 'none',
      height: 'auto',
    },
    '.cm-hybrid-mermaid-error': {
      margin: '0',
      color: 'var(--vscode-errorForeground, #f48771)',
      whiteSpace: 'pre-wrap',
    },
    '.cm-hybrid-codeblock': {
      display: 'block',
    },
    '.cm-line:has(.cm-hybrid-codeblock) > .cm-widgetBuffer, .cm-line:has(.cm-hybrid-codeblock-footer) > .cm-widgetBuffer': {
      display: 'none',
    },
    '.cm-hybrid-codeblock-inner': {
      borderTopLeftRadius: '4px',
      borderTopRightRadius: '4px',
      border: '0',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.12))',
      overflow: 'hidden',
    },
    '.cm-hybrid-codeblock-header': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: '1rem',
      minHeight: '1lh',
      lineHeight: 'inherit',
      padding: '0 12px',
    },
    '.cm-hybrid-codeblock-language': {
      color: 'var(--vscode-descriptionForeground)',
      fontSize: '0.82em',
      fontWeight: '600',
      lineHeight: 'inherit',
      letterSpacing: '0',
    },
    '.cm-hybrid-codeblock-copy': {
      border: '0',
      borderRadius: '4px',
      padding: '1px 6px',
      color: 'var(--vscode-descriptionForeground)',
      backgroundColor: 'transparent',
      font: 'inherit',
      fontSize: '0.82em',
      cursor: 'pointer',
      opacity: '0',
      pointerEvents: 'none',
    },
    '.cm-hybrid-codeblock:hover .cm-hybrid-codeblock-copy, .cm-hybrid-codeblock:focus-within .cm-hybrid-codeblock-copy': {
      opacity: '1',
      pointerEvents: 'auto',
    },
    '.cm-hybrid-codeblock-copy:hover': {
      color: 'var(--vscode-editor-foreground)',
      backgroundColor: 'color-mix(in srgb, var(--vscode-editor-foreground) 10%, transparent)',
    },
    '.cm-hybrid-codeblock-content-line': {
      boxSizing: 'border-box',
      paddingLeft: '14px',
      paddingRight: '14px',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.12))',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
      fontSize: '0.96em',
      lineHeight: 'inherit',
      color: 'var(--vscode-textPreformat-foreground, var(--vscode-editor-foreground))',
    },
    '.cm-hybrid-prism-token.token.comment, .cm-hybrid-prism-token.token.prolog, .cm-hybrid-prism-token.token.doctype, .cm-hybrid-prism-token.token.cdata': {
      color: 'var(--vscode-symbolIcon-colorForeground, #6a9955)',
      fontStyle: 'italic',
    },
    '.cm-hybrid-prism-token.token.keyword, .cm-hybrid-prism-token.token.atrule': {
      color: 'var(--vscode-symbolIcon-keywordForeground, #c586c0)',
      fontWeight: '600',
    },
    '.cm-hybrid-prism-token.token.string, .cm-hybrid-prism-token.token.char': {
      color: 'var(--vscode-symbolIcon-stringForeground, #ce9178)',
    },
    '.cm-hybrid-prism-token.token.function, .cm-hybrid-prism-token.token.method': {
      color: 'var(--vscode-symbolIcon-functionForeground, #dcdcaa)',
    },
    '.cm-hybrid-prism-token.token.number, .cm-hybrid-prism-token.token.boolean, .cm-hybrid-prism-token.token.constant': {
      color: 'var(--vscode-symbolIcon-numberForeground, #b5cea8)',
    },
    '.cm-hybrid-prism-token.token.operator, .cm-hybrid-prism-token.token.punctuation': {
      color: 'var(--vscode-descriptionForeground)',
    },
    '.cm-hybrid-prism-token.token.class-name, .cm-hybrid-prism-token.token.builtin, .cm-hybrid-prism-token.token.tag': {
      color: 'var(--vscode-symbolIcon-classForeground, #4ec9b0)',
    },
    '.cm-hybrid-prism-token.token.property, .cm-hybrid-prism-token.token.attr-name, .cm-hybrid-prism-token.token.selector': {
      color: 'var(--vscode-symbolIcon-propertyForeground, #9cdcfe)',
    },
    '.cm-hybrid-codeblock-footer': {
      display: 'block',
      boxSizing: 'border-box',
      minHeight: '1.15em',
      borderBottomLeftRadius: '4px',
      borderBottomRightRadius: '4px',
      backgroundColor: 'var(--vscode-textCodeBlock-background, rgba(127,127,127,.12))',
    },
    '.cm-hybrid-footnote-ref': {
      color: 'var(--vscode-textLink-foreground)',
      fontSize: '0.78em',
      verticalAlign: 'super',
      lineHeight: '0',
      fontWeight: '600',
    },
    '.cm-hybrid-footnote-def-label': {
      color: 'var(--vscode-textLink-foreground)',
      fontSize: '0.85em',
      verticalAlign: 'super',
      lineHeight: '0',
      fontWeight: '600',
    },
    '.cm-hybrid-footnote-def-separator': {
      color: 'var(--vscode-descriptionForeground)',
      fontSize: '0.85em',
      verticalAlign: 'super',
      lineHeight: '0',
      marginRight: '0.2em',
    },
    '.cm-hybrid-hr': {
      borderBottom: '1px solid var(--vscode-panel-border)',
      height: '0',
      margin: '0.75em 0',
    },
    '.cm-hybrid-table-widget': {
      display: 'block',
      padding: '0.45em 0 0.8em',
    },
    '.cm-hybrid-table-widget-inner': {
      display: 'block',
      overflowX: 'auto',
    },
    '.cm-hybrid-table': {
      borderCollapse: 'collapse',
      width: 'max-content',
      minWidth: 'min(100%, 28rem)',
      maxWidth: '100%',
      fontFamily: 'var(--vscode-font-family)',
      fontSize: 'var(--vscode-font-size)',
    },
    '.cm-hybrid-table th, .cm-hybrid-table td': {
      border: '1px solid var(--vscode-panel-border)',
      minWidth: '10ch',
      padding: '5px 9px',
      textAlign: 'left',
      verticalAlign: 'top',
      whiteSpace: 'pre-wrap',
    },
    '.cm-hybrid-table th': {
      fontWeight: '600',
      backgroundColor: 'var(--vscode-editor-lineHighlightBackground, rgba(127,127,127,.12))',
    },
    '.cm-hybrid-table-bold': { fontWeight: '700' },
    '.cm-hybrid-table-italic': { fontStyle: 'italic' },
    '.cm-hybrid-table-strike': { textDecoration: 'line-through', opacity: '0.75' },
    '.cm-hybrid-table-highlight': {
      backgroundColor: 'color-mix(in srgb, var(--vscode-editor-findMatchHighlightBackground, #ffd33d) 38%, transparent)',
      borderRadius: '2px',
      padding: '0 2px',
    },
    '.cm-hybrid-table-link': {
      appearance: 'none',
      border: '0',
      padding: '0',
      color: 'var(--vscode-textLink-foreground)',
      background: 'transparent',
      font: 'inherit',
      textDecoration: 'underline',
      cursor: 'pointer',
    },
    '.cm-hybrid-table-link:hover': {
      color: 'var(--vscode-textLink-activeForeground, var(--vscode-textLink-foreground))',
    },
    '.cm-hybrid-table-inline-code': {
      padding: '0.05em 0.28em',
      borderRadius: '3px',
      backgroundColor: 'var(--vscode-textCodeBlock-background)',
      color: 'var(--vscode-textPreformat-foreground, inherit)',
      fontFamily: 'var(--vscode-editor-font-family, ui-monospace, Menlo, monospace)',
    },
    '.cm-hybrid-table-inline-math': {
      display: 'inline',
      padding: '0',
      borderRadius: '0',
      backgroundColor: 'transparent',
    },
    '.cm-hybrid-table-inline-math mjx-container': {
      display: 'inline-block',
      margin: '0 0.08em',
      fontSize: '1.02em',
      color: 'var(--vscode-editor-foreground)',
      verticalAlign: 'middle',
    },
    '.cm-hybrid-table-inline-math mjx-container[jax="SVG"] > svg': {
      display: 'inline-block',
      verticalAlign: '-0.18em',
    },
  });
}
