#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from vaultlib import default_vault_root, parse_frontmatter, render_frontmatter

INDEX_FILE = "index.md"
LOG_FILE = "log.md"
ROOT_BUNDLE_DIRECTORIES = frozenset(
    {
        "comparisons",
        "concepts",
        "entities",
        "projects",
        "queries",
        "raw",
        "summaries",
    }
)
ROOT_BUNDLE_FILES = frozenset(
    {
        "AGENTS.md",
        "README.md",
        "SCHEMA.md",
        "index.md",
        "log.md",
    }
)
OPAQUE_DIRECTORIES = (Path("projects/code/nanochat"),)
GENERATED_WARNING = (
    "<!-- Generated by tools/okf/rebuild_indexes.py; "
    "do not edit by hand. -->"
)
DIRECTORY_DESCRIPTIONS = {
    "raw": "Immutable source evidence and local assets.",
    "raw/assets": "Archived PDFs and source media.",
    "projects": "Pinned software projects and their source checkouts.",
    "projects/code": "Opaque, exact-commit project source repositories.",
    "summaries": "Narrative entry points through the knowledge bundle.",
    "entities": "Named datasets, model families, and other concrete subjects.",
    "concepts": "Focused explanations of language-model mechanisms.",
    "comparisons": "Decision-oriented comparisons of related approaches.",
    "queries": "Durable answers to recurring reader questions.",
}


class IndexBuildError(RuntimeError):
    """Raised when metadata cannot support a deterministic OKF index."""


@dataclass(frozen=True)
class IndexRecord:
    section: str
    title: str
    link: str
    description: str


def _relative(vault_root: Path, path: Path) -> Path:
    return path.absolute().relative_to(vault_root.absolute())


def _is_opaque(vault_root: Path, path: Path) -> bool:
    relative = _relative(vault_root, path)
    return relative in OPAQUE_DIRECTORIES


def _is_hidden(path: Path) -> bool:
    return path.name.startswith(".") or path.name == "__pycache__"


def owned_directories(vault_root: Path) -> tuple[Path, ...]:
    """Return every visible bundle directory, excluding nested repositories."""
    vault_root = vault_root.absolute()
    if not vault_root.is_dir():
        return ()
    directories: list[Path] = []
    pending = [vault_root]
    while pending:
        directory = pending.pop()
        directories.append(directory)
        children = [
            child
            for child in directory.iterdir()
            if child.is_dir()
            and not child.is_symlink()
            and not _is_hidden(child)
            and not _is_opaque(vault_root, child)
            and (
                directory != vault_root
                or child.name in ROOT_BUNDLE_DIRECTORIES
            )
        ]
        pending.extend(sorted(children, reverse=True))
    return tuple(sorted(directories, key=lambda path: path.as_posix()))


def _concept_record(path: Path) -> IndexRecord:
    try:
        metadata = parse_frontmatter(
            path.read_text(encoding="utf-8"),
            source=path,
        ).metadata
    except (OSError, ValueError) as error:
        raise IndexBuildError(f"{path}: {error}") from error

    values: dict[str, str] = {}
    for key in ("type", "title", "description"):
        value = metadata.get(key)
        if not isinstance(value, str) or not value.strip():
            raise IndexBuildError(f"{path}: missing required {key}")
        values[key] = value.strip()
    return IndexRecord(
        section=values["type"],
        title=values["title"],
        link=path.name,
        description=values["description"],
    )


def _directory_description(vault_root: Path, directory: Path) -> str:
    relative = _relative(vault_root, directory).as_posix()
    if relative in DIRECTORY_DESCRIPTIONS:
        return DIRECTORY_DESCRIPTIONS[relative]
    label = directory.name.replace("-", " ").replace("_", " ")
    return f"Browse the {label} collection."


def _directory_record(vault_root: Path, directory: Path) -> IndexRecord:
    return IndexRecord(
        section="Subdirectories",
        title=directory.name,
        link=f"{directory.name}/",
        description=_directory_description(vault_root, directory),
    )


def _paper_pdf_record(vault_root: Path, path: Path) -> IndexRecord | None:
    raw_companion = vault_root / "raw" / f"{path.stem}.md"
    if path.parent != vault_root / "raw/assets" or not raw_companion.is_file():
        return None
    concept = _concept_record(raw_companion)
    return IndexRecord(
        section="Resources",
        title=f"{concept.title} — PDF",
        link=path.name,
        description=f"Archived PDF for {concept.title}.",
    )


def _project_for_source(
    vault_root: Path,
    source_directory: Path,
) -> tuple[str, str, str] | None:
    projects = vault_root / "projects"
    if not projects.is_dir():
        return None
    expected_source = _relative(projects, source_directory).as_posix()
    for path in sorted(projects.glob("*.md")):
        if path.name in {INDEX_FILE, LOG_FILE}:
            continue
        try:
            metadata = parse_frontmatter(
                path.read_text(encoding="utf-8"),
                source=path,
            ).metadata
        except (OSError, ValueError):
            continue
        if metadata.get("source_path") != expected_source:
            continue
        title = metadata.get("title")
        description = metadata.get("description")
        commit = metadata.get("pinned_commit")
        if all(
            isinstance(value, str) and value.strip()
            for value in (title, description, commit)
        ):
            return str(title).strip(), str(description).strip(), str(commit)
    return None


def _opaque_record(vault_root: Path, directory: Path) -> IndexRecord:
    project = _project_for_source(vault_root, directory)
    if project is None:
        raise IndexBuildError(
            f"{directory}: opaque source has no matching Software Project card"
        )
    title, _description, commit = project
    readme = directory / "README.md"
    link = f"{directory.name}/README.md" if readme.is_file() else f"{directory.name}/"
    return IndexRecord(
        section="Code Resources",
        title=f"{title} source",
        link=link,
        description=f"Pinned {title} source at {commit[:12]}.",
    )


def _resource_record(vault_root: Path, path: Path) -> IndexRecord:
    pdf_record = _paper_pdf_record(vault_root, path)
    if pdf_record is not None:
        return pdf_record
    suffix = path.suffix.lower().lstrip(".") or "file"
    return IndexRecord(
        section="Resources",
        title=path.name,
        link=path.name,
        description=f"Bundled {suffix} resource.",
    )


def child_records(
    directory: Path,
    vault_root: Path,
) -> tuple[IndexRecord, ...]:
    """Describe one directory's immediate visible children."""
    records: list[IndexRecord] = []
    for child in sorted(directory.iterdir(), key=lambda path: path.name.casefold()):
        if _is_hidden(child) or child.name == INDEX_FILE:
            continue
        if directory == vault_root:
            if child.is_dir() and child.name not in ROOT_BUNDLE_DIRECTORIES:
                continue
            if child.is_file() and child.name not in ROOT_BUNDLE_FILES:
                continue
        if child.is_dir():
            records.append(
                _opaque_record(vault_root, child)
                if _is_opaque(vault_root, child)
                else _directory_record(vault_root, child)
            )
            continue
        if child.name == LOG_FILE:
            records.append(
                IndexRecord(
                    section="Log",
                    title="Bundle history",
                    link=LOG_FILE,
                    description="Newest-first record of material bundle changes.",
                )
            )
            continue
        if child.suffix.lower() == ".md":
            records.append(_concept_record(child))
            continue
        records.append(_resource_record(vault_root, child))
    return tuple(records)


def _section_sort_key(section: str) -> tuple[int, str]:
    if section == "Subdirectories":
        return (0, section)
    if section in {"Resources", "Code Resources", "Log"}:
        return (2, section)
    return (1, section.casefold())


def build_index(
    directory: Path,
    vault_root: Path,
    records: tuple[IndexRecord, ...],
) -> str:
    grouped: dict[str, list[IndexRecord]] = defaultdict(list)
    for record in records:
        grouped[record.section].append(record)

    sections: list[str] = [GENERATED_WARNING]
    if not grouped:
        sections.extend(["# Contents", "", "* No entries yet."])
    else:
        for section in sorted(grouped, key=_section_sort_key):
            sections.extend([f"# {section}", ""])
            for record in sorted(
                grouped[section],
                key=lambda item: (item.title.casefold(), item.link),
            ):
                sections.append(
                    f"* [{record.title}]({record.link}) - {record.description}"
                )
            sections.append("")
        while sections and not sections[-1]:
            sections.pop()

    body = "\n".join(sections) + "\n"
    if directory.absolute() == vault_root.absolute():
        return render_frontmatter({"okf_version": "0.2"}, body)
    return body


def build_indexes(vault_root: Path) -> dict[Path, str]:
    """Render all hierarchical indexes without touching the filesystem."""
    vault_root = vault_root.absolute()
    outputs: dict[Path, str] = {}
    for directory in owned_directories(vault_root):
        records = child_records(directory, vault_root)
        outputs[directory / INDEX_FILE] = build_index(
            directory,
            vault_root,
            records,
        )
    return outputs


def update_indexes(vault_root: Path, *, check: bool) -> tuple[Path, ...]:
    """Check or write the complete deterministic index set."""
    vault_root = vault_root.absolute()
    outputs = build_indexes(vault_root)
    changed = tuple(
        path
        for path, expected in outputs.items()
        if not path.exists()
        or path.read_text(encoding="utf-8") != expected
    )
    if check:
        return changed
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path], encoding="utf-8", newline="\n")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild hierarchical indexes for the repository-root OKF bundle."
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--vault",
        type=Path,
        default=default_vault_root(),
    )
    arguments = parser.parse_args(argv)
    try:
        changed = update_indexes(arguments.vault, check=arguments.check)
    except IndexBuildError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        if changed:
            for path in changed:
                print(f"stale {path.relative_to(arguments.vault.absolute())}")
            return 1
        print("indexes up to date")
        return 0
    if changed:
        for path in changed:
            print(f"updated {path.relative_to(arguments.vault.absolute())}")
    else:
        print("indexes already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
